/**
 * Redirects for the WordPress site this one replaced, at the same domain.
 *
 * Taken from warcraft-gym.com's own Yoast sitemap (178 indexed URLs) and
 * matched against this site's sitemap: 116 old paths kept their slug through
 * the content migration and map one-to-one; the rest are sections, category
 * and tag archives placed by hand.
 *
 * Why every URL gets its own destination rather than a blanket rule to the
 * homepage: Google reads mass redirect-to-root as a soft 404 and drops the
 * pages instead of transferring their ranking. A redirect carries authority
 * only when it lands on the page that genuinely replaced the old one.
 *
 * Sources are written without a trailing slash. The old URLs all had one, and
 * Next normalises the slash away before matching, so a legacy link costs one
 * extra hop - well inside what crawlers follow.
 *
 * Permanent (308, which Google treats as 301). Keep them indefinitely: old
 * links live in Discord, forum posts and bookmarks for years, and the ranking
 * signal only transfers while the redirect still answers.
 */

export type LegacyRedirect = { source: string; destination: string; permanent: true };

export const LEGACY_REDIRECTS: LegacyRedirect[] = [
  // build orders (15)
  { source: "/1-aow-fast-hunts-tech", destination: "/learn/builds/1-aow-fast-hunts-tech", permanent: true },
  { source: "/24-food-proxy-expo", destination: "/learn/builds/24-food-proxy-expo", permanent: true },
  { source: "/dk-ghoul-expo-vs-ne", destination: "/learn/builds/dk-ghoul-expo-vs-ne", permanent: true },
  { source: "/dk-ghoul-tech-push-vs-kotg-dh-expo", destination: "/learn/builds/dk-ghoul-tech-push-vs-kotg-dh-expo", permanent: true },
  { source: "/dk-ghoul-tier-3-expo-vs-kotg-dh", destination: "/learn/builds/dk-ghoul-tier-3-expo-vs-kotg-dh", permanent: true },
  { source: "/facing-paladin-rifle-as-undead", destination: "/learn/builds/facing-paladin-rifle-as-undead", permanent: true },
  { source: "/farseer-1-grunt-into-headhunters", destination: "/learn/builds/farseer-1-grunt-into-headhunters", permanent: true },
  { source: "/farseer-fast-tech-without-barracks", destination: "/learn/builds/farseer-fast-tech-without-barracks", permanent: true },
  { source: "/ghoul-pull-build-vs-night-elf", destination: "/learn/builds/ghoul-pull-build-vs-night-elf", permanent: true },
  { source: "/mk-2-barracks-footmen-tower-rush", destination: "/learn/builds/mk-2-barracks-footmen-tower-rush", permanent: true },
  { source: "/no-barracks-shop-before-tech", destination: "/learn/builds/no-barracks-shop-before-tech", permanent: true },
  { source: "/paladin-rifle-build", destination: "/learn/builds/paladin-rifle-build", permanent: true },
  { source: "/quick-1-ziggurat-tech-into-gargoyles", destination: "/learn/builds/quick-1-ziggurat-tech-into-gargoyles", permanent: true },
  { source: "/solo-paladin-baptism-build", destination: "/learn/builds/solo-paladin-baptism-build", permanent: true },
  { source: "/two-burrow-tech-with-grunts", destination: "/learn/builds/two-burrow-tech-with-grunts", permanent: true },

  // guides (44)
  { source: "/1st-hero-naga-archer-dott-push", destination: "/learn/guide/1st-hero-naga-archer-dott-push", permanent: true },
  { source: "/a-summary-on-creep-mechanics-and-how-to-abuse-them", destination: "/learn/guide/a-summary-on-creep-mechanics-and-how-to-abuse-them", permanent: true },
  { source: "/amazonia-creep-routes", destination: "/learn/guide/amazonia-creep-routes", permanent: true },
  { source: "/an-overview-of-orc-upgrades", destination: "/learn/guide/an-overview-of-orc-upgrades", permanent: true },
  { source: "/ancient-of-war-creeping", destination: "/learn/guide/ancient-of-war-creeping", permanent: true },
  { source: "/archmage-first-one-creep-camp-into-expansion", destination: "/learn/guide/archmage-first-one-creep-camp-into-expansion", permanent: true },
  { source: "/attack-and-armor-types", destination: "/learn/guide/attack-and-armor-types", permanent: true },
  { source: "/autumn-leaves-2-0-and-its-changes", destination: "/learn/guide/autumn-leaves-2-0-and-its-changes", permanent: true },
  { source: "/autumn-leaves-creep-routes", destination: "/learn/guide/autumn-leaves-creep-routes", permanent: true },
  { source: "/body-blocking-and-surrounding-units", destination: "/learn/guide/body-blocking-and-surrounding-units", permanent: true },
  { source: "/concealed-hill-creep-routes", destination: "/learn/guide/concealed-hill-creep-routes", permanent: true },
  { source: "/cryptlord-fast-fiends-with-fast-tech", destination: "/learn/guide/cryptlord-fast-fiends-with-fast-tech", permanent: true },
  { source: "/damage-cap-and-unit-cap-on-spells", destination: "/learn/guide/damage-cap-and-unit-cap-on-spells", permanent: true },
  { source: "/death-knight-ghoul-tech-vs-dh-naga-panda-1-base", destination: "/learn/guide/death-knight-ghoul-tech-vs-dh-naga-panda-1-base", permanent: true },
  { source: "/demon-hunter-fast-bear-tech", destination: "/learn/guide/demon-hunter-fast-bear-tech", permanent: true },
  { source: "/echo-isles-creep-routes", destination: "/learn/guide/echo-isles-creep-routes", permanent: true },
  { source: "/farseer-headhunter-standard-2-burrow-tech", destination: "/learn/guide/farseer-headhunter-standard-2-burrow-tech", permanent: true },
  { source: "/fast-death-knight-with-fiends-build", destination: "/learn/guide/fast-death-knight-with-fiends-build", permanent: true },
  { source: "/fast-fiend-with-death-knight-build", destination: "/learn/guide/fast-fiend-with-death-knight-build", permanent: true },
  { source: "/fighting-paladin-rifle-as-ud-a-no-hands-guide-by-kaiser", destination: "/learn/guide/fighting-paladin-rifle-as-ud-a-no-hands-guide-by-kaiser", permanent: true },
  { source: "/hotkeys-in-warcraft", destination: "/learn/guide/hotkeys-in-warcraft", permanent: true },
  { source: "/hots-firelord-fast-expo-build", destination: "/learn/guide/hots-firelord-fast-expo-build", permanent: true },
  { source: "/how-hero-experience-works", destination: "/learn/guide/how-hero-experience-works", permanent: true },
  { source: "/human-base-building-guide", destination: "/learn/guide/human-base-building-guide", permanent: true },
  { source: "/human-beginner-rifle-caster", destination: "/learn/guide/human-beginner-rifle-caster", permanent: true },
  { source: "/item-levels-and-where-they-drop-on-ladder-maps", destination: "/learn/guide/item-levels-and-where-they-drop-on-ladder-maps", permanent: true },
  { source: "/last-refuge-creep-routes", destination: "/learn/guide/last-refuge-creep-routes", permanent: true },
  { source: "/mass-talons-versus-orc", destination: "/learn/guide/mass-talons-versus-orc", permanent: true },
  { source: "/northern-isles-creep-routes", destination: "/learn/guide/northern-isles-creep-routes", permanent: true },
  { source: "/pitlord-fast-t3-necro-wagon-push", destination: "/learn/guide/pitlord-fast-t3-necro-wagon-push", permanent: true },
  { source: "/quick-headhunters-and-slow-tauren-chieftain", destination: "/learn/guide/quick-headhunters-and-slow-tauren-chieftain", permanent: true },
  { source: "/shallow-graves-creep-routes", destination: "/learn/guide/shallow-graves-creep-routes", permanent: true },
  { source: "/shattered-exile-creep-routes", destination: "/learn/guide/shattered-exile-creep-routes", permanent: true },
  { source: "/standard-1-burrow-barracks-and-shop-before-tech", destination: "/learn/guide/standard-1-burrow-barracks-and-shop-before-tech", permanent: true },
  { source: "/standard-human-mirror-guide", destination: "/learn/guide/standard-human-mirror-guide", permanent: true },
  { source: "/tavern-hero-first-build-order-for-night-elf", destination: "/learn/guide/tavern-hero-first-build-order-for-night-elf", permanent: true },
  { source: "/terenas-stand-creep-routes", destination: "/learn/guide/terenas-stand-creep-routes", permanent: true },
  { source: "/tide-hunters-creep-routes", destination: "/learn/guide/tide-hunters-creep-routes", permanent: true },
  { source: "/tier-2-fs-naga-push-vs-ne", destination: "/learn/guide/tier-2-fs-naga-push-vs-ne", permanent: true },
  { source: "/turtle-rock-creep-routes", destination: "/learn/guide/turtle-rock-creep-routes", permanent: true },
  { source: "/undead-fast-dk-vs-blade-master-tips", destination: "/learn/guide/undead-fast-dk-vs-blade-master-tips", permanent: true },
  { source: "/warcraft-3-1v1-critter-spawns", destination: "/learn/guide/warcraft-3-1v1-critter-spawns", permanent: true },
  { source: "/warcraft-3-undead-base-layouts", destination: "/learn/guide/warcraft-3-undead-base-layouts", permanent: true },
  { source: "/wisp-positioning", destination: "/learn/guide/wisp-positioning", permanent: true },

  // sections, categories and tag archives (67)
  { source: "/category/news", destination: "/blog", permanent: true },
  { source: "/category/news/general", destination: "/blog", permanent: true },
  { source: "/category/news/gnl", destination: "/blog", permanent: true },
  { source: "/category/news/replays", destination: "/blog", permanent: true },
  { source: "/category/tutorials", destination: "/learn", permanent: true },
  { source: "/category/tutorials/creep-routes", destination: "/learn/creep-routes", permanent: true },
  { source: "/category/tutorials/human", destination: "/learn/human", permanent: true },
  { source: "/category/tutorials/night-elf", destination: "/learn/night-elf", permanent: true },
  { source: "/category/tutorials/orc", destination: "/learn/orc", permanent: true },
  { source: "/category/tutorials/tips-mechanics", destination: "/learn/mechanics", permanent: true },
  { source: "/category/tutorials/undead", destination: "/learn/undead", permanent: true },
  { source: "/category/uncategorized", destination: "/blog", permanent: true },
  { source: "/gnl-fantasy-league-s8-recap", destination: "/gnl/fantasy", permanent: true },
  { source: "/gnl/fantasy-league", destination: "/gnl/fantasy", permanent: true },
  { source: "/gnl/gnl-rules", destination: "/gnl/rules", permanent: true },
  { source: "/gnl/schedule-week-1", destination: "/gnl/schedule", permanent: true },
  { source: "/gnl/schedule-week-2", destination: "/gnl/schedule", permanent: true },
  { source: "/gnl/schedule-week-3", destination: "/gnl/schedule", permanent: true },
  { source: "/gnl/schedule-week-4", destination: "/gnl/schedule", permanent: true },
  { source: "/gnl/schedule-week-5", destination: "/gnl/schedule", permanent: true },
  { source: "/gnl/schedule-week-6", destination: "/gnl/schedule", permanent: true },
  { source: "/gnl/schedule-week-7", destination: "/gnl/schedule", permanent: true },
  { source: "/gyms-king-of-the-hill", destination: "/blog", permanent: true },
  { source: "/learn-warcraft-3", destination: "/learn", permanent: true },
  { source: "/learn-warcraft-3/game-mechanics", destination: "/learn/mechanics", permanent: true },
  { source: "/learn-warcraft-3/learn-human", destination: "/learn/human", permanent: true },
  { source: "/learn-warcraft-3/learn-night-elf", destination: "/learn/night-elf", permanent: true },
  { source: "/learn-warcraft-3/learn-orc", destination: "/learn/orc", permanent: true },
  { source: "/learn-warcraft-3/learn-undead", destination: "/learn/undead", permanent: true },
  { source: "/learn-warcraft-3/warcraft-3-creep-routes", destination: "/learn/creep-routes", permanent: true },
  { source: "/new-returning-players-guide-to-warcraft-iii", destination: "/learn/new-players", permanent: true },
  { source: "/news", destination: "/blog", permanent: true },
  { source: "/replays-of-the-month", destination: "/blog", permanent: true },
  { source: "/signup", destination: "/gnl/about", permanent: true },
  { source: "/tag/back2warcraft", destination: "/blog", permanent: true },
  { source: "/tag/barren", destination: "/blog", permanent: true },
  { source: "/tag/beginner-friendly", destination: "/learn/new-players", permanent: true },
  { source: "/tag/coaches", destination: "/blog", permanent: true },
  { source: "/tag/community", destination: "/blog", permanent: true },
  { source: "/tag/conclusion-cup", destination: "/blog", permanent: true },
  { source: "/tag/crypt-lord", destination: "/blog", permanent: true },
  { source: "/tag/fiends", destination: "/blog", permanent: true },
  { source: "/tag/floss2xdaily", destination: "/blog", permanent: true },
  { source: "/tag/fundraiser", destination: "/blog", permanent: true },
  { source: "/tag/gnl", destination: "/gnl/about", permanent: true },
  { source: "/tag/hot", destination: "/blog", permanent: true },
  { source: "/tag/hotwussy", destination: "/blog", permanent: true },
  { source: "/tag/human", destination: "/learn/human", permanent: true },
  { source: "/tag/human-build-orders", destination: "/learn/builds", permanent: true },
  { source: "/tag/intermediate", destination: "/blog", permanent: true },
  { source: "/tag/interview", destination: "/blog", permanent: true },
  { source: "/tag/kaiser", destination: "/blog", permanent: true },
  { source: "/tag/kaiser47", destination: "/blog", permanent: true },
  { source: "/tag/music-2", destination: "/blog", permanent: true },
  { source: "/tag/necromancers", destination: "/blog", permanent: true },
  { source: "/tag/orc", destination: "/learn/orc", permanent: true },
  { source: "/tag/paladin-rifle", destination: "/blog", permanent: true },
  { source: "/tag/pitlord", destination: "/blog", permanent: true },
  { source: "/tag/podcast", destination: "/blog", permanent: true },
  { source: "/tag/regulars", destination: "/blog", permanent: true },
  { source: "/tag/rigged", destination: "/blog", permanent: true },
  { source: "/tag/softicecream", destination: "/blog", permanent: true },
  { source: "/tag/sythren", destination: "/blog", permanent: true },
  { source: "/tag/tod", destination: "/blog", permanent: true },
  { source: "/tag/tutorial", destination: "/learn", permanent: true },
  { source: "/tag/undead", destination: "/learn/undead", permanent: true },
  { source: "/tag/warcraft-3", destination: "/blog", permanent: true },

  // posts (46)
  { source: "/creepcamp-vs-gym-newbie-league", destination: "/blog/creepcamp-vs-gym-newbie-league", permanent: true },
  { source: "/crit-happens-wins-gnl-s18", destination: "/blog/crit-happens-wins-gnl-s18", permanent: true },
  { source: "/drug-lords-wins-gnl-s17", destination: "/blog/drug-lords-wins-gnl-s17", permanent: true },
  { source: "/end-of-gnl-season-8-recap-bm-took-first-place", destination: "/blog/end-of-gnl-season-8-recap-bm-took-first-place", permanent: true },
  { source: "/fountain-of-manner-league-season-2-has-begun", destination: "/blog/fountain-of-manner-league-season-2-has-begun", permanent: true },
  { source: "/fuming-chicken-wins-gnl-s13", destination: "/blog/fuming-chicken-wins-gnl-s13", permanent: true },
  { source: "/giggling-goblins-got-the-last-laugh-gg-wins-gnl-s14", destination: "/blog/giggling-goblins-got-the-last-laugh-gg-wins-gnl-s14", permanent: true },
  { source: "/gnl-bears-win-gnl-s15", destination: "/blog/gnl-bears-win-gnl-s15", permanent: true },
  { source: "/gnl-cup-7-sign-ups-are-live", destination: "/blog/gnl-cup-7-sign-ups-are-live", permanent: true },
  { source: "/gnl-fantasy-league-s10-recap", destination: "/blog/gnl-fantasy-league-s10-recap", permanent: true },
  { source: "/gnl-fantasy-league-s8-week-1-update", destination: "/blog/gnl-fantasy-league-s8-week-1-update", permanent: true },
  { source: "/gnl-fantasy-league-s8-week-2-update", destination: "/blog/gnl-fantasy-league-s8-week-2-update", permanent: true },
  { source: "/gnl-fantasy-league-s8-week-3-update", destination: "/blog/gnl-fantasy-league-s8-week-3-update", permanent: true },
  { source: "/gnl-fantasy-league-s9-weeks-1-and-2-update", destination: "/blog/gnl-fantasy-league-s9-weeks-1-and-2-update", permanent: true },
  { source: "/gnl-fantasy-statistics", destination: "/blog/gnl-fantasy-statistics", permanent: true },
  { source: "/gnl-s12-fantasy-league-recap", destination: "/blog/gnl-s12-fantasy-league-recap", permanent: true },
  { source: "/gnl-s7-deaddumble-monkees-vs-savior-sit-casted-by-barren-bidoux", destination: "/blog/gnl-s7-deaddumble-monkees-vs-savior-sit-casted-by-barren-bidoux", permanent: true },
  { source: "/gnl-s8-team-announcements-s8-schedule-and-more", destination: "/blog/gnl-s8-team-announcements-s8-schedule-and-more", permanent: true },
  { source: "/gnl-season-14-fantasy-wrap-up", destination: "/blog/gnl-season-14-fantasy-wrap-up", permanent: true },
  { source: "/gnl-season-7-conclusion-cups", destination: "/blog/gnl-season-7-conclusion-cups", permanent: true },
  { source: "/gnl-season-7-team-announcement", destination: "/blog/gnl-season-7-team-announcement", permanent: true },
  { source: "/gnl-season-8-conclusion-cup", destination: "/blog/gnl-season-8-conclusion-cup", permanent: true },
  { source: "/gotquails-week-1-fantasy-update", destination: "/blog/gotquails-week-1-fantasy-update", permanent: true },
  { source: "/gym-newbie-league-vs-wandering-dragons", destination: "/blog/gym-newbie-league-vs-wandering-dragons", permanent: true },
  { source: "/gyms-koth-masters-edition", destination: "/blog/gyms-koth-masters-edition", permanent: true },
  { source: "/ill-light-the-way-fundraiser-for-hot", destination: "/blog/ill-light-the-way-fundraiser-for-hot", permanent: true },
  { source: "/intense-focus-wins-gnl-s12", destination: "/blog/intense-focus-wins-gnl-s12", permanent: true },
  { source: "/introducing-the-b-team", destination: "/blog/introducing-the-b-team", permanent: true },
  { source: "/introducing-the-gym-learning-center-tutorials-builds-creep-routes", destination: "/blog/introducing-the-gym-learning-center-tutorials-builds-creep-routes", permanent: true },
  { source: "/jabba-lick-team-wins-gnl-s10", destination: "/blog/jabba-lick-team-wins-gnl-s10", permanent: true },
  { source: "/kevinwc3-takes-the-crown-in-gyms-first-koth-masters-edition", destination: "/blog/kevinwc3-takes-the-crown-in-gyms-first-koth-masters-edition", permanent: true },
  { source: "/meet-the-gym-commissioner-barren-rigged", destination: "/blog/meet-the-gym-commissioner-barren-rigged", permanent: true },
  { source: "/meet-the-gym-kaiser47", destination: "/blog/meet-the-gym-kaiser47", permanent: true },
  { source: "/meet-the-gym-sythren", destination: "/blog/meet-the-gym-sythren", permanent: true },
  { source: "/meet-the-gym-the-captains", destination: "/blog/meet-the-gym-the-captains", permanent: true },
  { source: "/ne-ark-vs-ne-acccreate-september-replay-of-the-month", destination: "/blog/ne-ark-vs-ne-acccreate-september-replay-of-the-month", permanent: true },
  { source: "/ne-glaive-vs-ud-pearlmoose-august-replay-of-the-month", destination: "/blog/ne-glaive-vs-ud-pearlmoose-august-replay-of-the-month", permanent: true },
  { source: "/ne-link-vs-ud-moissan-replay-of-the-month-aug-26", destination: "/blog/ne-link-vs-ud-moissan-replay-of-the-month-aug-26", permanent: true },
  { source: "/orc-creep-routes-have-been-added", destination: "/blog/orc-creep-routes-have-been-added", permanent: true },
  { source: "/orc-disengage-vs-ne-ally-replay-of-the-month-aug-23", destination: "/blog/orc-disengage-vs-ne-ally-replay-of-the-month-aug-23", permanent: true },
  { source: "/pitty-party-wins-gnl-s16", destination: "/blog/pitty-party-wins-gnl-s16", permanent: true },
  { source: "/prism-vs-theocdrummer-game-of-the-gym-koth", destination: "/blog/prism-vs-theocdrummer-game-of-the-gym-koth", permanent: true },
  { source: "/signups-are-open-for-gnl-season-11", destination: "/blog/signups-are-open-for-gnl-season-11", permanent: true },
  { source: "/small-losses-wins-gnl-s11", destination: "/blog/small-losses-wins-gnl-s11", permanent: true },
  { source: "/team-cok-crowned-kings-of-gnl-season-7", destination: "/blog/team-cok-crowned-kings-of-gnl-season-7", permanent: true },
  { source: "/ud-sheik-vs-ne-razermoon-october-replay-of-the-month", destination: "/blog/ud-sheik-vs-ne-razermoon-october-replay-of-the-month", permanent: true },
];
