/** W3Champions hero ids (from match payloads) to the site's icon keys. */
export const W3C_HEROES: Record<string, { icon: string; label: string }> = {
  archmage: { icon: "hu-archmage", label: "Archmage" },
  paladin: { icon: "hu-paladin", label: "Paladin" },
  mountainking: { icon: "hu-mountain-king", label: "Mountain King" },
  // W3Champions calls the Blood Mage "sorceror" (the hero's internal name);
  // it is never the Sorceress unit, which is not a hero.
  sorceror: { icon: "hu-blood-mage", label: "Blood Mage" },
  bloodmage: { icon: "hu-blood-mage", label: "Blood Mage" },
  forsakenpaladin: { icon: "hu-forsaken-paladin", label: "Forsaken Paladin" },
  blademaster: { icon: "or-blademaster", label: "Blademaster" },
  farseer: { icon: "or-far-seer", label: "Far Seer" },
  taurenchieftain: { icon: "or-tauren-chieftain", label: "Tauren Chieftain" },
  shadowhunter: { icon: "or-shadow-hunter", label: "Shadow Hunter" },
  demonhunter: { icon: "ne-demon-hunter", label: "Demon Hunter" },
  keeperofthegrove: { icon: "ne-keeper-of-the-grove", label: "Keeper of the Grove" },
  priestessofthemoon: { icon: "ne-priestess-of-the-moon", label: "Priestess of the Moon" },
  warden: { icon: "ne-warden", label: "Warden" },
  deathknight: { icon: "ud-death-knight", label: "Death Knight" },
  lich: { icon: "ud-lich", label: "Lich" },
  dreadlord: { icon: "ud-dreadlord", label: "Dreadlord" },
  cryptlord: { icon: "ud-crypt-lord", label: "Crypt Lord" },
  seawitch: { icon: "nt-naga-sea-witch", label: "Naga Sea Witch" },
  bansheeranger: { icon: "nt-dark-ranger", label: "Dark Ranger" },
  pandarenbrewmaster: { icon: "nt-pandaren-brewmaster", label: "Pandaren Brewmaster" },
  beastmaster: { icon: "nt-beastmaster", label: "Beastmaster" },
  pitlord: { icon: "nt-pit-lord", label: "Pit Lord" },
  tinker: { icon: "nt-goblin-tinker", label: "Goblin Tinker" },
  avatarofflame: { icon: "nt-firelord", label: "Firelord" },
  alchemist: { icon: "nt-goblin-alchemist", label: "Goblin Alchemist" },
};
