import type { BuildOrder } from "./types";

/** Seed builds for local dev and as the fallback when Sanity is unreachable.
 *  Timings and supply counts are representative, not tournament-precise. */
export const FIXTURE_BUILDS: BuildOrder[] = [
  {
    slug: "human-fast-expand-archmage-rifles",
    title: "Archmage fast expand into Rifles",
    race: "human",
    vsRace: "any",
    difficulty: "beginner",
    patch: "2.0.3",
    tags: ["fast expand", "rifles", "standard"],
    summary:
      "The safe Human standard: Archmage first, creep a camp, expand early behind Militia, then Rifles and a Blacksmith.",
    author: "Gym Coaches",
    maintainer: "Gym Coaches",
    featured: true,
    publishedAt: "2026-08-20T10:00:00Z",
    updatedAt: "2026-09-10T10:00:00Z",
    steps: [
      { time: "0:00", supply: 5, instruction: "4 Peasants to gold, 1 builds Altar of Kings", icon: "hu-altar" },
      { time: "0:05", supply: 5, instruction: "Queue 2 Peasants", icon: "hu-peasant" },
      { time: "0:20", supply: 6, instruction: "New Peasant builds Farm", icon: "hu-farm" },
      { time: "0:35", supply: 7, instruction: "Peasant builds Barracks", icon: "hu-barracks" },
      { time: "1:05", supply: 8, instruction: "Farm", icon: "hu-farm" },
      { time: "1:30", supply: 9, instruction: "Archmage: Water Elemental first", icon: "hu-archmage" },
      { time: "1:45", supply: 11, instruction: "2 Footmen, creep the closest green camp", icon: "hu-footman" },
      { time: "2:30", supply: 14, instruction: "Lumber Mill", icon: "hu-lumber-mill" },
      { time: "3:00", supply: 15, instruction: "Town Hall at the natural, 3 Militia to guard", icon: "hu-town-hall" },
      { time: "3:40", supply: 17, instruction: "Blacksmith, then Rifleman production", icon: "hu-blacksmith" },
      { time: "4:30", supply: 21, instruction: "Keep, second hero from Altar", icon: "hu-keep" },
      { time: "5:30", supply: 26, instruction: "Long Rifles, 2 Farms, keep creeping", icon: "hu-rifleman" },
    ],
    description: [
      "This is the opening every Human should own before anything fancier. The Archmage's Water Elemental lets you creep without losses, and the early expansion pays for everything that comes after.",
      "Expand between 3:00 and 3:30 depending on the map. If you scout an early aggression hero (Blademaster, Demon Hunter), delay the expansion and add a Tower first.",
      "Transition: Priests + Sorceresses from Arcane Sanctum once Keep finishes, or Knights vs Undead.",
    ],
  },
  {
    slug: "orc-far-seer-headhunter-timing",
    title: "Far Seer Headhunter timing push",
    race: "orc",
    vsRace: "human",
    difficulty: "intermediate",
    patch: "2.0.3",
    tags: ["headhunters", "timing", "aggression"],
    summary:
      "Far Seer with wolves, quick Headhunters and a Burrow-heavy economy, hitting the Human expansion before Keep finishes.",
    author: "Gym Coaches",
    featured: false,
    publishedAt: "2026-08-28T10:00:00Z",
    updatedAt: "2026-08-28T10:00:00Z",
    steps: [
      { time: "0:00", supply: 5, instruction: "4 Peons to gold, 1 builds Altar of Storms", icon: "or-altar" },
      { time: "0:05", supply: 5, instruction: "Queue 2 Peons", icon: "or-peon" },
      { time: "0:25", supply: 6, instruction: "Burrow", icon: "or-burrow" },
      { time: "0:40", supply: 7, instruction: "Barracks", icon: "or-barracks" },
      { time: "1:20", supply: 8, instruction: "Far Seer: Feral Spirit first", icon: "or-far-seer" },
      { time: "1:40", supply: 10, instruction: "Grunt, creep with wolves", icon: "or-grunt" },
      { time: "2:10", supply: 12, instruction: "War Mill, second Burrow", icon: "or-war-mill" },
      { time: "2:40", supply: 14, instruction: "Troll Headhunters non-stop from Barracks", icon: "or-headhunter" },
      { time: "3:20", supply: 18, instruction: "Stronghold", icon: "or-stronghold" },
      { time: "4:00", supply: 22, instruction: "Second Barracks, Burrow", icon: "or-barracks" },
      { time: "4:45", supply: 28, instruction: "Ranged upgrade, move out with 8–10 Headhunters", icon: "nt-attack" },
      { time: "5:30", supply: 32, instruction: "Hit the expansion before Keep completes", icon: "nt-expansion" },
    ],
    description: [
      "The point is the timing: you arrive at the Human natural while Militia are still the only defence. Bring the Far Seer's wolves to tank tower shots and focus the Town Hall.",
      "If the Human went Tower-heavy instead of expanding, don't commit, pull back, take your own expansion and switch to Raiders.",
    ],
  },
  {
    slug: "nightelf-tavern-hero-hunts",
    title: "Tavern hero into Huntresses",
    race: "nightelf",
    vsRace: "orc",
    difficulty: "intermediate",
    patch: "2.0.3",
    tags: ["tavern", "huntress", "map control"],
    summary:
      "Skip the Altar: buy a Tavern hero (Beastmaster or Dark Ranger), creep hard early and pump Huntresses from two Ancients of War.",
    author: "Gym Coaches",
    featured: false,
    publishedAt: "2026-09-02T10:00:00Z",
    updatedAt: "2026-09-02T10:00:00Z",
    steps: [
      { time: "0:00", supply: 5, instruction: "4 Wisps to gold, 1 builds Ancient of War", icon: "ne-ancient-of-war" },
      { time: "0:05", supply: 5, instruction: "Queue 2 Wisps", icon: "ne-wisp" },
      { time: "0:20", supply: 6, instruction: "Moon Well", icon: "ne-moon-well" },
      { time: "0:45", supply: 7, instruction: "Wisp walks to Tavern", icon: "nt-tavern" },
      { time: "1:10", supply: 8, instruction: "Buy Beastmaster (or Dark Ranger vs Orc)", icon: "nt-beastmaster" },
      { time: "1:30", supply: 9, instruction: "Second Ancient of War", icon: "ne-ancient-of-war" },
      { time: "1:50", supply: 11, instruction: "Huntress from AoW 1, Moon Well", icon: "ne-huntress" },
      { time: "2:30", supply: 14, instruction: "Hunter's Hall", icon: "ne-hunters-hall" },
      { time: "3:10", supply: 18, instruction: "Huntresses from both AoWs, creep the map", icon: "ne-huntress" },
      { time: "4:00", supply: 24, instruction: "Tree of Ages, Moon Wells to 5", icon: "ne-tree-of-ages" },
      { time: "5:00", supply: 30, instruction: "Second hero from Altar of Elders", icon: "ne-altar" },
    ],
    description: [
      "Tavern heroes let you creep faster than an Altar opening and keep the Orc guessing. Beastmaster's Quilbeast summons make early creeping free; Dark Ranger's Silence punishes Far Seer wolves.",
      "Keep Huntresses grouped, they win fights on surround, not stats.",
    ],
  },
  {
    slug: "undead-fast-death-knight-fiends",
    title: "Fast Death Knight into Crypt Fiends",
    race: "undead",
    vsRace: "nightelf",
    difficulty: "beginner",
    patch: "2.0.3",
    tags: ["fiends", "standard", "safe"],
    summary:
      "The Undead bread and butter: Death Knight as early as possible, Ghouls on wood, Fiends from two Crypts, Halls at 30 food.",
    author: "Gym Coaches",
    featured: false,
    publishedAt: "2026-09-08T10:00:00Z",
    updatedAt: "2026-09-08T10:00:00Z",
    steps: [
      { time: "0:00", supply: 5, instruction: "3 Acolytes to gold, 1 builds Crypt, 1 builds Altar", icon: "ud-altar" },
      { time: "0:05", supply: 5, instruction: "Ghoul to lumber", icon: "ud-ghoul" },
      { time: "0:20", supply: 6, instruction: "Acolyte builds Ziggurat", icon: "ud-ziggurat" },
      { time: "0:50", supply: 7, instruction: "Queue Acolyte, then 2 Ghouls from Crypt", icon: "ud-ghoul" },
      { time: "1:15", supply: 9, instruction: "Death Knight: Death Coil first", icon: "ud-death-knight" },
      { time: "1:40", supply: 11, instruction: "Graveyard, Ziggurat", icon: "ud-graveyard" },
      { time: "2:20", supply: 14, instruction: "Creep with DK + 3 Ghouls, Crypt Fiends start", icon: "ud-crypt-fiend" },
      { time: "3:00", supply: 17, instruction: "Second Crypt, Ziggurat", icon: "ud-crypt" },
      { time: "3:40", supply: 21, instruction: "Halls of the Dead", icon: "ud-halls-of-the-dead" },
      { time: "4:30", supply: 26, instruction: "Fiends from both Crypts, Web when Halls finish", icon: "ud-crypt-fiend" },
      { time: "5:30", supply: 32, instruction: "Lich from Altar, Slaughterhouse for Statues", icon: "ud-lich" },
    ],
    description: [
      "Learn this before any other Undead build. Ghouls on lumber from the first minute is the single biggest economic habit; never let the wood run dry.",
      "Vs Night Elf, Web is the priority research, Hippogryphs and Talons are the threats Fiends exist to answer.",
    ],
  },
];
