// Generated by scripts/creep-maps/add-map.mjs — do not edit by hand.
//
// One static import per catalogue in this directory. `fixtures.mjs` reads
// `RAW_MAPS` from here; `fixtures.test.mjs` fails if this file and the
// directory disagree.

import autumnLeaves from "./autumn-leaves.json" with { type: "json" };
import echoIsles from "./echo-isles.json" with { type: "json" };
import fadingAutumn from "./fading-autumn.json" with { type: "json" };
import hammerfall from "./hammerfall.json" with { type: "json" };
import lastRefuge from "./last-refuge.json" with { type: "json" };
import northernIsles from "./northern-isles.json" with { type: "json" };
import scrimmage from "./scrimmage.json" with { type: "json" };
import shallowGrave from "./shallow-grave.json" with { type: "json" };
import springtime from "./springtime.json" with { type: "json" };
import tidehunters from "./tidehunters.json" with { type: "json" };
import turtleRock from "./turtle-rock.json" with { type: "json" };
import twistedMeadows from "./twisted-meadows.json" with { type: "json" };

export const RAW_MAPS = {
  "autumn-leaves": autumnLeaves,
  "echo-isles": echoIsles,
  "fading-autumn": fadingAutumn,
  "hammerfall": hammerfall,
  "last-refuge": lastRefuge,
  "northern-isles": northernIsles,
  "scrimmage": scrimmage,
  "shallow-grave": shallowGrave,
  "springtime": springtime,
  "tidehunters": tidehunters,
  "turtle-rock": turtleRock,
  "twisted-meadows": twistedMeadows,
};
