import type { BuildRace } from "@/lib/builds/types";

export type CreepRouteRace = BuildRace;

export type RouteLevel = "standard" | "beginner";

export const ROUTE_LEVELS: { id: RouteLevel; label: string }[] = [
  { id: "beginner", label: "Beginner" },
  { id: "standard", label: "Standard" },
];

/** A camp's possible item drop, resolved from its creeps' drop tables (see
 *  `scripts/creep-maps/drops.mjs`): either a random pool (`class`+`level`,
 *  e.g. "Permanent level 3") or a single concrete item (`id`). `items` is
 *  the expanded, ready-to-render list for that pool/item — empty when the
 *  catalogue was built without the `item-table.mjs` source files (see
 *  `build.mjs`'s header comment). */
export type MapCampDrop = {
  kind: "class" | "item";
  class?: string;
  level?: number;
  id?: string;
  chance: number;
  items: { id: string; name: string; icon: string }[];
};

/** One creep camp as generated by `scripts/creep-maps/build.mjs` into
 *  `src/lib/creep-routes/maps/<slug>.json`. `x`/`y` are minimap-normalised
 *  [0,1]; `worldX`/`worldY` are the in-game coordinates. `level`/`xp`/`band`
 *  are the camp's own totals (sum of its creeps' levels, sum of their base
 *  xp, and a difficulty label), not a hero's. `drops` (F011) is the union
 *  of every creep's possible item drops, deduped — see `MapCampDrop`. */
export type MapCamp = {
  id: string;
  x: number;
  y: number;
  worldX: number;
  worldY: number;
  creeps: { id: string; name: string; level: number; count: number; icon: string }[];
  level: number;
  xp: number;
  band: string;
  sleeps: boolean;
  drops: MapCampDrop[];
};

export type MapStart = { player: number; x: number; y: number; worldX: number; worldY: number };
export type MapMine = { x: number; y: number; worldX: number; worldY: number; gold: number };
export type MapShop = { id: string; x: number; y: number };

/** A creep-route map: the catalogue shape from `maps/*.json`, plus
 *  `minimapUrl` (`/maps/<slug>.png` for fixtures; the Sanity image URL once
 *  a map is published there). */
export type CreepMap = {
  slug: string;
  name: string;
  mapVersion?: string;
  w3cMapId: number;
  /** Playable-rect bounds (terrain minus the map's unplayable border) —
   *  what camp/start/mine/shop `x`/`y` are normalised against. See
   *  `docs/creep-routes.md`'s "The playable rectangle". */
  bounds: { xMin: number; xMax: number; yMin: number; yMax: number };
  /** Raw terrain-grid bounds, wider than `bounds`; reference-only, not used
   *  for any coordinate math on the site. */
  terrainBounds?: { xMin: number; xMax: number; yMin: number; yMax: number };
  /** The `.w3i` camera bounds quad (four `x,y` corner pairs, flattened);
   *  reference-only, carried straight through from the catalogue. */
  cameraBounds?: number[];
  image: { width: number; height: number };
  camps: MapCamp[];
  starts: MapStart[];
  mines: MapMine[];
  shops: MapShop[];
  minimapUrl: string;
  /** Provenance, carried through from the catalogue when present. */
  sourceFile?: string;
  generatedAt?: string;
};

/** One step of a route. `campId: null` marks a base action between camps
 *  (TP home, buy from a shop, take the expansion) — `action` names it. A
 *  camp stop instead names the camp being cleared; `units` (if present)
 *  describes what the player brings, not the camp's contents (those live on
 *  the map's `camps[]`, looked up by `campId`). A route has no time
 *  dimension: it is an ordered list of stops, nothing more — see
 *  `docs/creep-routes.md`'s "XP model" for how stop *order* alone drives
 *  the hero level/xp readout. */
export type RouteStop = {
  campId: string | null;
  action?: string;
  units?: { icon: string; count: number }[];
  note?: string;
  condition?: string;
};

export type CreepRoute = {
  slug: string;
  title: string;
  race: BuildRace;
  /** Opponent races the route is written for; empty means any opponent. */
  vsRaces: BuildRace[];
  level: RouteLevel;
  /** `minimapUrl` is the map's own band-free minimap thumbnail — carried
   *  alongside `slug`/`name` so a route list/detail surface can show it
   *  without a second `CreepMap` fetch (F009-followup-2: "the map is the
   *  second-level heading on every route surface"). Optional because older
   *  callers/fixtures may not populate it. */
  map: { slug: string; name: string; minimapUrl?: string };
  /** Index into `map.starts` — which spawn is *your* base. Unset/0 (the
   *  default) is fine for every two-start map; only a map with more than
   *  two spawns (Turtle Rock, Twisted Meadows) ever needs this set. The
   *  opponent's base is never recorded — every other entry in
   *  `map.starts` draws as the small muted "opponent" marker. */
  start?: number;
  /** Icon key into GAME_ICON_OPTIONS (src/lib/builds/icons.ts), optional. */
  hero?: string;
  summary: string;
  author: string;
  authorDiscord?: string;
  maintainer?: string;
  sourceUrl?: string;
  /** Optional link to a companion build order. */
  build?: { slug: string; title: string } | null;
  patch?: string;
  /** The catalogue `mapVersion` this route was written against, if known. */
  mapVersion?: string;
  /** Shown as chips on the list row and the detail page, exactly like
   *  builds' own `tags` (F009). Persistence (a Sanity field, editor
   *  submission) is F010 — today only the fixtures carry any. */
  tags?: string[];
  featured: boolean;
  publishedAt: string;
  updatedAt: string;
  stops: RouteStop[];
  /** Portable Text blocks (from Sanity) or plain paragraphs (fixtures). */
  description?: unknown[] | string[];
};
