/** Creep and hero experience, sourced from Blizzard's own game data:
 * `Units/MiscGame.txt`, patch 1.27.1 enUS, mirrored at
 * https://raw.githubusercontent.com/sumneko/w3x2lni/master/data/enUS-1.27.1/mpq/Custom_V1/Units/MiscGame.txt
 *
 * Every number below is generated by constants in that file rather than
 * transcribed from a table:
 *
 *   GrantNormalXP=25             a level-1 creep is worth 25
 *   GrantNormalXPFormulaB=5      each further creep level adds 5*L + 5
 *   GrantNormalXPFormulaC=5
 *   NeedHeroXP=200               a hero needs 200 to reach level 2
 *   NeedHeroXPFormulaB=100       each further hero level costs 100*L more
 *   NeedHeroXPFormulaC=0
 *   HeroFactorXP=80,70,60,50,0   the share kept at hero level 1,2,3,4,5+
 *
 * `xp.test.mjs` re-derives the whole table from those constants and fails on
 * any disagreement, so the citation is checked rather than asserted. (The
 * same values appear at
 * https://warcraft.wiki.gg/wiki/Hero_(Warcraft_III)#Experience — useful as a
 * second opinion, but the game files are the source of truth here: a
 * wiki-sourced creep table shipped earlier in this project disagreed with the
 * SLK data on 26 of 83 entries.)
 *
 * A hero killing a creep gains XP per creep, tapered by how far the hero has
 * already levelled past the creeps guarding it.
 */

/** Levels 1-6, generated by the formula above from `GrantNormalXP`. */
const CREEP_XP_BASE = [25, 40, 60, 85, 115, 150];

/** XP a hero gets for killing one creep of `level` (levels 1-6 from the
 * table, 7+ by `GrantNormalXPFormula`'s recurrence: previous + 5*(level+1),
 * i.e. B*L + C with B = C = 5). */
export function creepXp(level) {
  if (level < 1) throw new Error(`creepXp: level must be >= 1, got ${level}`);
  if (level <= CREEP_XP_BASE.length) return CREEP_XP_BASE[level - 1];
  let xp = CREEP_XP_BASE[CREEP_XP_BASE.length - 1];
  for (let l = CREEP_XP_BASE.length + 1; l <= level; l++) {
    xp += 5 * (l + 1);
  }
  return xp;
}

/** Cumulative XP a hero needs to *be* `level` (level 1 needs 0; each step
 * from n-1 to n costs 100*n more — `NeedHeroXPFormulaB` = 100, C = 0, which
 * reproduces `NeedHeroXP` = 200 for level 2). */
export function heroXpForLevel(level) {
  if (level < 1) throw new Error(`heroXpForLevel: level must be >= 1, got ${level}`);
  let xp = 0;
  for (let l = 2; l <= level; l++) {
    xp += 100 * l;
  }
  return xp;
}

/** The share of a creep's XP a hero still gets at `heroLevel`, straight from
 * `HeroFactorXP=80,70,60,50,0`: full value only applies to level 0 (unused
 * here); by level 1 a hero already keeps only 0.8, tapering to 0 from level
 * 5 on. */
export function creepXpFactor(heroLevel) {
  const factors = { 1: 0.8, 2: 0.7, 3: 0.6, 4: 0.5 };
  return factors[heroLevel] ?? 0;
}

function levelForXp(xp) {
  let level = 1;
  while (heroXpForLevel(level + 1) <= xp) {
    level++;
  }
  return level;
}

/** Folds a hero through `camps` (each an array of creep levels, in camp
 * order) starting at `startLevel`, applying `creepXpFactor` to every kill
 * at the hero's *current* level — Blizzard's reduction factor applies per
 * kill, not once per camp (`MiscGame.txt`'s `HeroFactorXP` is read at the
 * moment of each kill; see docs/creep-routes.md's "XP model") — so the
 * hero can level up mid-camp and the rest of that camp's kills already pay
 * the new, lower factor.
 *
 * Returns `{ level, xp }` after each camp (`perCamp`) and overall.
 */
export function heroLevelAfter(camps, startLevel = 1) {
  let level = startLevel;
  let xp = heroXpForLevel(startLevel);
  const perCamp = [];

  for (const camp of camps) {
    for (const creepLevel of camp) {
      const factor = creepXpFactor(level);
      // Warcraft III awards whole XP: floor each creep's grant (not the
      // running total) — our modelling choice, see docs/creep-routes.md.
      xp += Math.floor(creepXp(creepLevel) * factor);
      level = levelForXp(xp);
    }
    perCamp.push({ level, xp });
  }

  return { level, xp, perCamp };
}
