#!/usr/bin/env node
/**
 * One command for "add or update a map".
 *
 *   pnpm maps:add path/to/1v1_NewMap_v1.0@1234.w3x   # add (or replace) one
 *   pnpm maps:rebuild                                 # rebuild every map
 *
 * Copies any given archive into `map-sources/`, then rebuilds everything
 * downstream from *all* of `map-sources/`, so the checked-in catalogues are
 * always the product of the checked-in inputs:
 *
 *   1. collect every creep rawcode the maps place
 *   2. creeps.json   from Blizzard's unit tables, for exactly those ids
 *   3. catalogues    + minimap PNGs (build.mjs)
 *   4. items.json    from Blizzard's item tables, for the pools they drop
 *   5. icons         fetched for anything new (skip with --no-icons)
 *   6. maps/index.mjs regenerated so fixtures pick the map up
 *
 * Blizzard's tables are cached under `node_modules/.cache/` on first run;
 * they are patch-1.27.1 game data, not ours to check in, and only the
 * distilled `creeps.json`/`items.json` live in the repo.
 *
 * Deliberately not a "fill in the gaps by hand" flow: if a map places a creep
 * Blizzard's tables do not describe, this stops and names the rawcode.
 * Creep level silently drives camp level, XP, difficulty band and the whole
 * hero-level projection, so a plausible guess there is worse than a failure.
 */
import { execFileSync } from "node:child_process";
import { copyFileSync, existsSync, mkdirSync, readdirSync, writeFileSync, rmSync } from "node:fs";
import { basename, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("../../", import.meta.url));
const SOURCES = join(ROOT, "map-sources");
const CATALOGUES = join(ROOT, "src/lib/creep-routes/maps");
const PUBLIC_MAPS = join(ROOT, "public/maps");
const CACHE = join(ROOT, "node_modules/.cache/wc3-game-data");
const SCRATCH = join(ROOT, "node_modules/.cache/creep-maps-build");

const MIRROR = "https://raw.githubusercontent.com/sumneko/w3x2lni/master/data/enUS-1.27.1/mpq";
/** Blizzard game data. `unitdata.slk` lives outside `Custom_V1`. */
const GAME_DATA = {
  "neutralunitstrings.txt": `${MIRROR}/Custom_V1/Units/neutralunitstrings.txt`,
  "neutralunitfunc.txt": `${MIRROR}/Custom_V1/Units/neutralunitfunc.txt`,
  "unitbalance.slk": `${MIRROR}/Custom_V1/Units/unitbalance.slk`,
  "itemdata.slk": `${MIRROR}/Custom_V1/Units/itemdata.slk`,
  "itemstrings.txt": `${MIRROR}/Custom_V1/Units/itemstrings.txt`,
  "itemfunc.txt": `${MIRROR}/Custom_V1/Units/itemfunc.txt`,
  "unitdata.slk": `${MIRROR}/Units/unitdata.slk`,
};

const step = (n, what) => console.log(`\n[${n}/6] ${what}`);
const run = (args) => execFileSync("node", args, { cwd: ROOT, stdio: "inherit" });

function parseArgs(argv) {
  const files = [];
  let icons = true;
  for (const arg of argv) {
    if (arg === "--no-icons") icons = false;
    else if (arg.startsWith("--")) throw new Error(`unknown argument: ${arg}`);
    else files.push(arg);
  }
  return { files, icons };
}

async function cacheGameData() {
  mkdirSync(CACHE, { recursive: true });
  const paths = {};
  for (const [name, url] of Object.entries(GAME_DATA)) {
    const target = join(CACHE, name);
    if (!existsSync(target)) {
      const res = await fetch(url);
      if (!res.ok) throw new Error(`GET ${url} -> ${res.status}`);
      writeFileSync(target, Buffer.from(await res.arrayBuffer()));
      console.log(`  fetched ${name}`);
    }
    paths[name] = target;
  }
  return paths;
}

function mapFiles() {
  const files = readdirSync(SOURCES).filter((f) => /\.w3[xm]$/i.test(f));
  if (files.length === 0) throw new Error(`no .w3x/.w3m files in ${SOURCES}`);
  return files.map((f) => join(SOURCES, f));
}

/** Every rawcode the maps place as a hostile creep — the exact id set
 *  `creeps.json` must cover, so the table is neither short nor padded. */
async function creepIds(files) {
  const { openMap, readMember } = await import("./mpq.mjs");
  const { parseUnitsDoo } = await import("./units-doo.mjs");
  const ids = new Set();
  for (const file of files) {
    const doo = parseUnitsDoo(readMember(openMap(file), "war3mapUnits.doo"));
    for (const unit of doo.units) if (unit.player === 24) ids.add(unit.typeId);
  }
  return [...ids].sort();
}

/** `fixtures.mjs` needs a static import per catalogue (the bundler cannot
 *  read a directory), so the list is generated rather than hand-maintained —
 *  forgetting an entry was how Northern Isles went missing once. */
function writeMapsIndex() {
  const slugs = readdirSync(CATALOGUES)
    .filter((f) => f.endsWith(".json"))
    .map((f) => f.replace(/\.json$/, ""))
    .sort();
  const ident = (slug) => slug.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
  const body = [
    "// Generated by scripts/creep-maps/add-map.mjs — do not edit by hand.",
    "//",
    "// One static import per catalogue in this directory. `fixtures.mjs` reads",
    "// `RAW_MAPS` from here; `fixtures.test.mjs` fails if this file and the",
    "// directory disagree.",
    "",
    ...slugs.map((s) => `import ${ident(s)} from "./${s}.json" with { type: "json" };`),
    "",
    "export const RAW_MAPS = {",
    ...slugs.map((s) => `  "${s}": ${ident(s)},`),
    "};",
    "",
  ].join("\n");
  writeFileSync(join(CATALOGUES, "index.mjs"), body);
  return slugs;
}

async function main() {
  const { files: incoming, icons } = parseArgs(process.argv.slice(2));

  mkdirSync(SOURCES, { recursive: true });
  for (const file of incoming) {
    const from = resolve(file);
    if (!existsSync(from)) throw new Error(`no such file: ${from}`);
    if (!/\.w3[xm]$/i.test(from)) throw new Error(`not a map archive: ${from}`);
    copyFileSync(from, join(SOURCES, basename(from)));
    console.log(`added ${basename(from)} to map-sources/`);
  }

  const maps = mapFiles();
  console.log(`\nrebuilding ${maps.length} map(s) from map-sources/`);

  step(1, "caching Blizzard game data");
  const data = await cacheGameData();

  step(2, "creeps.json");
  const ids = await creepIds(maps);
  const idsFile = join(CACHE, "creep-ids.json");
  writeFileSync(idsFile, JSON.stringify(ids, null, 1));
  console.log(`  ${ids.length} distinct creep rawcodes placed`);
  run([
    "scripts/creep-maps/creep-table.mjs",
    "--strings", data["neutralunitstrings.txt"],
    "--balance", data["unitbalance.slk"],
    "--data", data["unitdata.slk"],
    "--func", data["neutralunitfunc.txt"],
    "--ids", idsFile,
    "--out", "src/lib/creep-routes/creeps.json",
  ]);

  step(3, "catalogues and minimaps");
  rmSync(SCRATCH, { recursive: true, force: true });
  const pool = join(SOURCES, "pool.json");
  run([
    "scripts/creep-maps/build.mjs",
    ...maps,
    ...(existsSync(pool) ? ["--pool", pool] : []),
    "--itemdata", data["itemdata.slk"],
    "--itemstrings", data["itemstrings.txt"],
    "--itemfunc", data["itemfunc.txt"],
    "--out", SCRATCH,
  ]);
  mkdirSync(CATALOGUES, { recursive: true });
  mkdirSync(PUBLIC_MAPS, { recursive: true });
  for (const f of readdirSync(SCRATCH)) {
    if (f.endsWith(".json")) copyFileSync(join(SCRATCH, f), join(CATALOGUES, f));
    else if (f.endsWith(".png")) copyFileSync(join(SCRATCH, f), join(PUBLIC_MAPS, f));
  }

  step(4, "items.json");
  run([
    "scripts/creep-maps/item-table.mjs",
    "--itemdata", data["itemdata.slk"],
    "--itemstrings", data["itemstrings.txt"],
    "--itemfunc", data["itemfunc.txt"],
    "--out", "src/lib/creep-routes/items.json",
  ]);

  step(5, icons ? "icons" : "icons (skipped)");
  if (icons) run(["scripts/creep-maps/fetch-icons.mjs", "--scratch", join(CACHE, "icons")]);

  step(6, "maps/index.mjs");
  const slugs = writeMapsIndex();
  console.log(`  ${slugs.length} catalogues registered`);

  console.log("\nDone. Next: `pnpm test`, review the diff, commit, then");
  console.log("`node scripts/creep-maps/publish.mjs --all` to push to Sanity.");
}

main().catch((err) => {
  console.error(`\n${err.message}`);
  process.exit(1);
});
