/**
 * Human build orders transcribed from the Warcraft-gym.com build cards that
 * sit inside the Learn guides. Steps: [supply, icon key, instruction, time?].
 * See to-ndjson.mjs for the import.
 */
export const BUILDS = [
  {
    slug: "beginner-rifle-caster",
    title: "Beginner Rifle Caster",
    guideId: "guide-6871",
    vsRace: "any",
    difficulty: "beginner",
    tags: ["riflemen", "priests", "standard", "beginner"],
    summary:
      "The timeless Human opener for new players: Archmage, Footmen, Keep at 29 food, then Riflemen, Priests and a Mountain King for a 50 food midgame attack. Decent in every matchup and on every map.",
    description: [
      "Rifle caster is a timeless classic for Human. The idea is to build towards a midgame power spike of Riflemen and Priests and then go attack the opponent. Its real strength is flexibility: it is decent in every matchup and on every map, which makes it ideal for beginners and an excellent way to practise fundamentals like executing a build, creeping and microing a fight.",
      "Weak early game and slow to move, so expect to be harassed and set up fights patiently. Two benchmarks: the Keep should start around 3:10 (17:30 on the in-game clock), and at 7:20 (dawn of day two) you should be at 49-50 food with upgrades on the way.",
    ],
    steps: [
      ["5/12", "hu-peasant", "Make a Peasant and keep producing them. 4 Peasants mine gold, 1 builds an Altar."],
      ["6/12", "hu-barracks", "1st new Peasant builds a Barracks."],
      ["7/12", "hu-farm", "2nd new Peasant builds a Farm."],
      ["8/12", "nt-gold", "3rd new Peasant mines gold."],
      ["9/12", "hu-farm", "4th new Peasant builds a Farm."],
      ["10/18", "hu-archmage", "Altar finishes: train the Archmage."],
      ["16/18", "hu-footman", "Barracks finishes: train a Footman and keep producing them."],
      ["18/18", "hu-farm", "Build a Farm."],
      ["21/24", "nt-scout", "First Footman spawns: use it to scout the opponent."],
      ["21/24", "hu-scout-tower", "Build a Scout Tower."],
      ["22/24", "hu-peasant", "Pause Peasant production."],
      ["22/24", "hu-militia", "Archmage spawns: call 5 Militia and start creeping."],
      ["24/30", "hu-arcane-tower", "Upgrade the Scout Tower to an Arcane Tower."],
      ["24/30", "hu-peasant", "Make one final Peasant. You should have 14 in total: 5 on gold, 9 on lumber."],
      ["29/30", "hu-footman", "Stop making Footmen. You should have 5 in total."],
      ["29/30", "hu-keep", "Upgrade the Town Hall to a Keep. Benchmark: around 3:10, ten seconds before nightfall.", "3:10"],
      ["29/30", "nt-upgrade", "As soon as you have the resources: Defend, Arcane Vault, Blacksmith, Farm, Farm."],
      ["?/30", "hu-rifleman", "Blacksmith finishes: start Rifleman production."],
      ["?/40", "hu-mountain-king", "Keep finishes: Mountain King, then an Arcane Sanctum (power build it with 2 Peasants)."],
      ["?/50", "hu-priest", "Arcane Sanctum finishes: start Priest production."],
      ["?/50", "nt-upgrade", "Research whenever you can: Long Rifles, Priest Adept Training, +1 ranged attack."],
      ["50/50", "nt-attack", "Benchmark 7:20, dawn of day two: 49-50 food with upgrades on the way. Position carefully and go attack.", "7:20"],
    ],
  },
  {
    slug: "paladin-rifle-build",
    title: "Paladin Rifle Build",
    guideId: "guide-1064",
    vsRace: "undead",
    difficulty: "intermediate",
    tags: ["paladin", "riflemen", "blood mage", "sustain"],
    summary:
      "Blacksmith before Barracks, Paladin at 12 food and Riflemen from 18: a sustain build around Holy Light and Devotion Aura, with the Blood Mage feeding mana at tier 2. Strongest versus Undead.",
    description: [
      "The Paladin Rifle build revolves around sustainability. The Human balances feeding mana to the Paladin with the Blood Mage while draining the mana of the enemy heroes, all the while keeping the Riflemen alive with Holy Light by balancing the damage each takes. Versus Undead in particular, Holy Light and later Resurrection turn every fight.",
      "It can work at all levels. It is not friendly for those just learning the game because it plays so differently from other Human builds, but once you get the hang of it, it is easier to execute.",
    ],
    steps: [
      ["5/12", "hu-peasant", "Send 4 of your first Peasants to gold and 1 to wood."],
      ["5/12", "hu-peasant", "Queue up 4 Peasants."],
      ["7/12", "nt-lumber", "Send the 1st created Peasant to wood."],
      ["7/12", "hu-altar", "When the 1st created Peasant mines 10 wood and returns it, build an Altar."],
      ["8/12", "hu-blacksmith", "With the 2nd created Peasant start a Farm; at roughly 100 hit points stop building it and build a Blacksmith with that Peasant."],
      ["9/12", "hu-barracks", "The 3rd created Peasant builds a Barracks. Queue up a Peasant (5th of the game)."],
      ["10/12", "hu-farm", "The 4th created Peasant finishes the Farm."],
      ["10/12", "hu-peasant", "Queue another Peasant."],
      ["10/12", "nt-gold", "When you have 20 wood, take the Peasant on wood and put it on gold for 5 total on gold."],
      ["11/12", "hu-farm", "The 5th created Peasant builds a 2nd Farm."],
      ["11/12", "hu-peasant", "Queue another Peasant. The 6th created Peasant goes to wood."],
      ["12/18", "hu-paladin", "Build a Paladin. All Peasants that were building go to mine wood after."],
      ["17/18", "hu-peasant", "Queue a Peasant (8 queued so far). 5 on gold and 8 will be on wood."],
      ["18/24", "hu-rifleman", "Build a Rifleman."],
      ["21/24", "hu-rifleman", "Queue a 2nd Rifleman as soon as you have the resources."],
      ["21/24", "hu-farm", "Build a 3rd Farm with a wood Peasant as soon as you have the resources."],
      ["24/24", "hu-militia", "Paladin and first Rifle are out. Use 2 wood Peasants as Militia to help creep small camps."],
      ["24/24", "hu-paladin", "The Paladin skills Holy Light and Devotion Aura: Holy Light at levels 1 and 3."],
      ["24/30", "hu-keep", "Tech to tier 2 as soon as you have the resources."],
      ["24/30", "nt-scout", "Scout the enemy with one wood Peasant in Militia form."],
      ["24/30", "hu-rifleman", "Build a 3rd Rifleman. Continue creeping with Paladin and Riflemen."],
      ["27/30", "hu-scout-tower", "Build a 4th Rifleman, a Farm and a Scout Tower in main (upgrade the tower if necessary)."],
      ["30/36", "nt-upgrade", "Build another Rifleman (29/36 if the scout died). Start +1 attack for ranged units."],
      ["33/36", "hu-farm", "Build a Farm."],
      ["33/42", "hu-blood-mage", "When tier 2 finishes get the Blood Mage and Long Rifles. The Paladin should be level 3 or near it."],
      ["38/42", "hu-peasant", "Queue more wood Peasants (amount depends on your game plan) and build a Farm."],
      ["38/42", "nt-upgrade", "Get the level 1 armour upgrade for Riflemen."],
      ["39/42", "nt-creep", "Begin power creeping your Blood Mage after the Paladin hits level 3. Siphon Mana levels are critical."],
      ["?/50", "hu-rifleman", "From 40 food continue making Riflemen and decide how you will approach the late game."],
    ],
  },
  {
    slug: "mk-2-barracks-footmen-tower-rush",
    title: "MK 2 Barracks Footmen Tower Rush",
    guideId: "guide-2970",
    vsRace: "any",
    difficulty: "advanced",
    tags: ["tower rush", "mountain king", "footmen", "all-in", "cheese"],
    summary:
      "An all-in: Mountain King and Footmen from two Barracks, Defend researched, then four Militia run across the map at nightfall to tower the enemy base while the Footmen stream in.",
    description: [
      "The MK 2 Barracks tower push relies on heavy micro and out-microing your opponent while staying calm. It is an all-in: you need to win with the initial push, otherwise your opponent will out-scale and out-tech your tier 1 army. On maps like Echo Isles there is a variant with one Barracks and mass mercenaries.",
      "This can work at all levels; it comes down to execution. Gym members have reached 1700 MMR with it and pros like Fortitude have won with it. Your opening is the same as a standard Human build, which we recommend perfecting first.",
    ],
    steps: [
      ["5/12", "hu-altar", "Send 4 of your first Peasants to gold, 1 starts a Farm. Right after starting it, use that Peasant to build an Altar, then send it to wood."],
      ["5/12", "hu-peasant", "Queue 2 Peasants."],
      ["6/12", "hu-barracks", "Send your 1st Peasant created to build a Barracks, then to wood when finished."],
      ["7/12", "hu-farm", "Send your 2nd Peasant created to continue building the 1st Farm, then to wood when finished."],
      ["7/12", "hu-peasant", "Queue 2 Peasants."],
      ["8/12", "nt-gold", "Send your 3rd Peasant created to the gold mine and rally your 4th Peasant to the gold mine."],
      ["9/12", "hu-farm", "When the 4th Peasant is half trained, send 1 Peasant from gold to build a 2nd Farm and shift-click it to build a 3rd Farm after."],
      ["9/12", "hu-peasant", "Queue 2 Peasants. When the 4th Peasant is created you put it on gold and have 5/5 on gold."],
      ["10/12", "nt-lumber", "Send the 5th Peasant created to wood."],
      ["11/18", "hu-mountain-king", "Make your Mountain King and the 1st Footman."],
      ["18/18", "hu-peasant", "Queue 1 Peasant."],
      ["19/24", "hu-footman", "Make the 2nd Footman."],
      ["21/24", "hu-peasant", "Queue 1 Peasant."],
      ["22/24", "hu-farm", "Make the 4th Farm with the Peasant that built the 3rd. Remember to Militia creep when the MK is out."],
      ["22/30", "hu-barracks", "Build the 2nd Barracks and produce the 3rd Footman when available."],
      ["24/30", "hu-peasant", "Queue 1 Peasant."],
      ["25/30", "hu-lumber-mill", "Build a Lumber Mill."],
      ["25/36", "nt-upgrade", "Research Defend."],
      ["25/36", "hu-militia", "Keep building Footmen. When night falls, pull 4 Militia and start running across to the enemy base."],
      ["?/36", "nt-goblin-merchant", "Stop at the Goblin Merchant with your hero: sell all items, buy Boots of Speed, a Circlet and Dust if against Night Elf."],
      ["?/36", "hu-arcane-tower", "Keep building Footmen from both Barracks, go to the enemy base and start towers: an Arcane Tower first, then Guard Towers."],
      ["?/36", "hu-farm", "Add more Farms if you are supply blocked and have not lost many units."],
      ["?/36", "hu-mountain-king", "Once you hit level 2 on the MK, skill level 1 Bash."],
    ],
  },
  {
    slug: "archmage-one-camp-into-expansion",
    title: "Archmage One Camp into Expansion",
    guideId: "guide-5014",
    vsRace: "any",
    difficulty: "beginner",
    tags: ["fast expand", "archmage", "footmen", "militia"],
    summary:
      "Archmage and Footmen creep one camp with Militia, then five more Militia meet the army at the natural and build the Town Hall at 28 food. Flexible into any two-base play.",
    description: [
      "A very common and flexible expansion build that works on most maps. You quickly creep one camp before expanding, which gives you some extra safety compared to an immediate expansion, and it can transition into any two-base play. Most commonly used against Undead and Night Elf, whose usual harass timings give you enough time to creep one camp first.",
      "Always keep a Peasant in production until the stopping point, and unless stated otherwise every Peasant that builds goes to lumber after. It is a little map dependent: you want a creep camp between your main and the expansion.",
    ],
    steps: [
      ["5/12", "hu-altar", "Send 4 Peasants to gold, 1 builds an Altar of Kings. Train one Peasant at your Town Hall."],
      ["6/12", "hu-barracks", "1st Peasant builds a Barracks."],
      ["7/12", "hu-farm", "2nd Peasant builds a Farm."],
      ["8/12", "nt-gold", "3rd Peasant mines gold."],
      ["9/12", "hu-farm", "4th Peasant builds a Farm."],
      ["10/18", "hu-archmage", "Altar finishes: start training an Archmage."],
      ["15/18", "nt-lumber", "All Peasants from here on are rallied to lumber."],
      ["16/18", "hu-footman", "Barracks finishes: start training a Footman. Keep producing Footmen until the stopping point."],
      ["18/18", "hu-farm", "When you have 20 lumber, build your third Farm."],
      ["21/24", "nt-scout", "First Footman finishes: send it to scout the enemy."],
      ["22/24", "hu-militia", "When the Archmage is about to finish, call 3 Militia and creep the first camp with the Archmage and 2nd Footman."],
      ["27/30", "hu-militia", "About halfway through the first camp, call 5 Militia from your main and send them to the expansion. They link up as you finish the camp."],
      ["28/30", "hu-peasant", "Stop production of Footmen and Peasants. You should have 15 Peasants (5 gold, 5 lumber, 5 creeping the expansion), 4 Footmen and 1 Archmage."],
      ["28/30", "hu-town-hall", "After creeping the expansion, build a Town Hall with 4 Peasants and a Scout Tower with 1. Upgrade the tower to an Arcane Tower when it finishes."],
      ["28/30", "hu-peasant", "Make Peasants if you expect to be harassed, or a 5th Footman if you want to be aggressive. When in doubt: make Peasants."],
    ],
  },
  {
    slug: "solo-paladin-baptism-build",
    title: "Solo Paladin Baptism Build",
    guideId: "guide-5624",
    vsRace: "undead",
    difficulty: "advanced",
    tags: ["paladin", "footmen", "expansion", "towers", "hit and run"],
    summary:
      "Paladin and Footmen hit and run the Undead buildings while you expand at 24 food behind an Arcane Tower and mass towers on both bases. Static defence holds; the army does not.",
    author: "DarkDestroy",
    description: [
      "Written by DarkDestroy/TheRedOrc. The Solo Paladin build is effective only against Undead and relies on hit and run with buildings as the primary target. You need to out-micro the opponent early and lean on static defences to hold pushes, since your army will not beat theirs head on.",
      "This can work at all levels; it comes down to execution, and Gym members have reached 1700 MMR with it. The opening is the same as a standard Human build, which we recommend perfecting first.",
    ],
    steps: [
      ["5/12", "hu-altar", "Send 4 of your first Peasants to gold, 1 begins a Farm, stops, then builds an Altar. Send it to wood after the Altar."],
      ["5/12", "hu-peasant", "Queue 2 Peasants."],
      ["6/12", "hu-barracks", "Send your 1st Peasant created to build a Barracks, then to wood when finished."],
      ["7/12", "hu-farm", "Send your 2nd Peasant created to continue building the 1st Farm, then to wood when finished."],
      ["7/12", "hu-peasant", "Queue 2 more Peasants."],
      ["8/12", "nt-gold", "Send your 3rd Peasant to the gold mine and rally your 4th Peasant to the gold mine."],
      ["9/12", "hu-farm", "When the 4th Peasant is half trained, take 1 Peasant from gold to build a 2nd Farm and queue a 3rd Farm after it."],
      ["9/12", "hu-peasant", "Queue 2 Peasants. When the 4th Peasant is created put it on gold for 5/5. All other Peasants mine wood."],
      ["11/18", "hu-paladin", "Make your hero, the Paladin."],
      ["18/18", "hu-peasant", "Queue 1 Peasant."],
      ["19/24", "hu-footman", "Make the 2nd Footman."],
      ["21/24", "hu-peasant", "Queue 1 Peasant."],
      ["22/24", "hu-farm", "Make the 4th Farm with the Peasant building the 3rd. Militia creep when the Paladin is out, and take an instant expansion if possible."],
      ["22/30", "hu-footman", "Produce the 3rd Footman when available."],
      ["24/30", "hu-town-hall", "Drop a Town Hall and an Arcane Tower."],
      ["24/30", "hu-peasant", "Produce 3 Peasants and the 4th Footman."],
      ["29/36", "hu-keep", "If the opponent has scouted you, keep producing Peasants and play defensively; otherwise you can tech."],
      ["?/36", "hu-guard-tower", "Build a Lumber Mill and start massing towers once the tech has started. You need at least 5 towers on each base."],
      ["?/36", "nt-lumber", "Assess whether you need a Goblin Shredder for wood."],
    ],
  },
  {
    slug: "standard-human-mirror-build",
    title: "Standard Human Mirror Build",
    guideId: "guide-6271",
    vsRace: "human",
    difficulty: "intermediate",
    tags: ["mirror", "footmen", "breakers", "priests", "standard"],
    summary:
      "The standard Human mirror: Archmage Footmen, tech at 30 food around nightfall, Mountain King second, two Arcane Sanctums into Priests and Spell Breakers, then expand between 40 and 50 food.",
    description: [
      "The standard way to open the Human mirror. Always keep a Peasant in production until the stopping point, and unless stated otherwise every Peasant that builds goes to lumber after. Benchmark: the tier 2 tech should start around nightfall, 18:00 on the in-game clock.",
      "Your 50 food army should be about 15 Peasants, 2 heroes, 4-5 Priests and the rest Spell Breakers plus any surviving Footmen. Expand between 40 and 50 food, add a Blacksmith for 2/2 Breaker upgrades, and tech tier 3 for Knights, Paladin and Staff of Sanctuary once you have an edge.",
    ],
    steps: [
      ["5/12", "hu-altar", "Send 4 Peasants to gold, 1 builds an Altar of Kings. Train 1 Peasant at your Town Hall."],
      ["6/12", "hu-barracks", "1st Peasant builds a Barracks."],
      ["7/12", "hu-farm", "2nd Peasant builds a Farm."],
      ["8/12", "nt-gold", "3rd Peasant mines gold."],
      ["9/12", "hu-farm", "4th Peasant builds a Farm. All new Peasants from here on harvest lumber."],
      ["10/18", "hu-archmage", "Altar finishes: start training an Archmage."],
      ["16/18", "hu-footman", "Barracks finishes: train a Footman and keep producing them until the stopping point. The Barracks Peasant builds the third Farm."],
      ["19/24", "hu-scout-tower", "When your second Farm finishes, build a Scout Tower with the same Peasant."],
      ["21/24", "nt-scout", "First Footman finishes: send it to scout the enemy."],
      ["22/24", "hu-militia", "When the Archmage spawns, call Militia and creep your first camp with the Archmage and 2nd Footman."],
      ["28/30", "hu-peasant", "Stop producing Peasants. You should have 15 in total: 5 on gold, 10 on lumber."],
      ["28/30", "hu-arcane-tower", "Upgrade your Scout Tower to an Arcane Tower."],
      ["30/30", "hu-keep", "Tech to tier 2 as soon as you can afford it. Benchmark: around nightfall, 18:00 on the in-game clock."],
      ["30/30", "nt-upgrade", "After starting the tech, spend in this order: Boots of Speed on the Archmage, Arcane Vault, Lumber Mill, 2 Farms."],
      ["?/40", "hu-mountain-king", "When tier 2 finishes get a second hero (when in doubt, Mountain King) and build two Arcane Sanctums, each power built with one extra Peasant."],
      ["?/50", "hu-priest", "When the Sanctums finish start making Priests. Start Priest Adept Training after the third. After five Priests, start making Spell Breakers."],
      ["?/50", "nt-expansion", "Expand somewhere between 40 and 50 food, then strengthen the lumber economy with about 2 Peasants or a Shredder."],
      ["?/50", "hu-blacksmith", "After expanding start a Blacksmith and get your Breakers to 2/2 (order: 1/0, 1/1, 2/1, then 2/2)."],
      ["?/70", "hu-castle", "When you have an advantage, tech tier 3 for Knights, a Paladin and Staff of Sanctuary."],
    ],
  },
];
