/**
 * Night Elf build orders transcribed from the Warcraft-gym.com build cards
 * that sit inside the Learn guides. Steps: [supply, icon key, instruction].
 * See to-ndjson.mjs for the import.
 */
export const BUILDS = [
  {
    slug: "demon-hunter-fast-tech-bears",
    title: "Demon Hunter Fast Tech Bears",
    guideId: "guide-1276",
    vsRace: "any",
    difficulty: "beginner",
    tags: ["bears", "demon hunter", "fast tech", "standard", "safe"],
    summary:
      "The safest Night Elf build: Demon Hunter, four Archers and an Ancient of War creep, tech at 21 food, Hunter's Hall and two Ancients of Lore, then Master Druids of the Claw and an Orb of Venom.",
    description: [
      "The standard fast Master Druid of the Claw strategy is one of the first things a Night Elf player should learn: it is probably the safest build against most opponents and works in every matchup to varying degrees, especially with a Demon Hunter. The strength comes from the Demon Hunter preventing the opponent from playing out their game while you tech.",
      "Easy to execute, though it can be used in strategies that are advanced. It also works with a Keeper of the Grove first, but this version sticks to Demon Hunter first for the least variance.",
    ],
    steps: [
      ["5/10", "ne-altar", "Put 4 of the starting Wisps on gold and have the 5th Wisp build an Altar."],
      ["5/10", "ne-wisp", "Build your 1st Wisp."],
      ["6/10", "ne-ancient-of-war", "Take a Wisp from your gold mine when the 1st queued Wisp is 2/3 done and build an Ancient of War, ideally in position to creep."],
      ["6/10", "ne-wisp", "Queue your 2nd Wisp."],
      ["6/10", "ne-moon-well", "The 1st Wisp created builds a Moon Well."],
      ["7/10", "nt-gold", "Queue your 3rd Wisp. Your 2nd and 3rd Wisps go to the gold mine for 5/5 on gold. All future Wisps go to wood."],
      ["8/10", "ne-wisp", "Queue your 4th Wisp."],
      ["8/10", "nt-scout", "Scout with the Wisp that built the Altar and send the Wisp that made the Moon Well to harvest lumber."],
      ["9/10", "ne-demon-hunter", "Build your first hero (usually Demon Hunter, sometimes Keeper). Continue Wisps until you have 9 on wood in total."],
      ["15/20", "ne-archer", "Build an Archer."],
      ["18/20", "ne-moon-well", "Build a Moon Well once you hit 40 wood."],
      ["19/20", "nt-creep", "When the Archer completes, begin the Ancient of War creep."],
      ["20/20", "ne-ancient-of-wonders", "Your 9th wood Wisp is stuck in queue: start an Ancient of Wonders with a wood Wisp to drop to 19/20, then cancel it once the Wisp starts training."],
      ["21/30", "ne-tree-of-ages", "Build a 2nd Archer. Tech to tier 2 (you should have 5 on gold, 9 on wood, 2 Archers and 1 hero)."],
      ["23/30", "ne-archer", "Build a 3rd Archer."],
      ["25/30", "ne-moon-well", "Build a Moon Well when you have enough lumber."],
      ["25/30", "ne-archer", "Build a 4th Archer."],
      ["27/30", "ne-hunters-hall", "When your tier 2 tech is 50% complete build a Hunter's Hall."],
      ["27/30", "ne-ancient-of-lore", "When tier 2 and the Hunter's Hall finish, build 1 Ancient of Lore and a wood Wisp."],
      ["28/40", "ne-tree-of-eternity", "Begin your tech to tier 3."],
      ["28/40", "nt-tavern", "Buy your second hero (common choices are Naga, Panda or Keeper)."],
      ["33/40", "ne-ancient-of-lore", "When you have enough lumber build a 2nd Ancient of Lore and then your shop."],
      ["33/40", "ne-dryad", "When the Ancient of Lore finishes build a Dryad."],
      ["36/40", "ne-druid-of-the-claw", "Begin pumping Bears. Get Adept training before tier 3. When tier 3 finishes get Master training as soon as possible and an Orb of Venom for one hero."],
    ],
  },
  {
    slug: "firelord-fast-expo",
    title: "Firelord Fast Expo",
    guideId: "guide-1406",
    vsRace: "any",
    difficulty: "advanced",
    tags: ["fast expand", "firelord", "archers", "tavern hero"],
    summary:
      "HoT's special: Tree of Life planted at the natural at 7 food, a Tavern Firelord whose Lava Spawns creep the expansion, Archers to hold, then a two-base tech to Marksmanship and Mountain Giants.",
    author: "HoT",
    description: [
      "The Firelord fast expo is HoT's latest special and probably the fastest expansion build in the game from a build start perspective. It takes advantage of being able to sustain early pressure with Lava Spawns: with good control, a Firelord, Archers and some Wisps can hold off most early aggression while the second base pays off.",
      "Advanced. The whole build depends on holding the expansion with very little.",
    ],
    steps: [
      ["5/10", "nt-lumber", "Move all 5 Wisps to wood, but 1 harvests where you will place your Tree of Life (near your natural expansion)."],
      ["5/10", "ne-wisp", "Build 2 Wisps and send both to gold."],
      ["7/10", "ne-tree-of-life", "Once you hit 185 wood build the Tree of Life, move 3 Wisps to gold and keep 1 on wood."],
      ["6/10", "ne-wisp", "Queue up 4 more Wisps which all go to lumber."],
      ["10/10", "ne-altar", "Build an Altar at 50 lumber and then an Ancient of War at 60 lumber."],
      ["9/10", "ne-wisp", "Build 2 Wisps which go to lumber."],
      ["10/10", "ne-ancient-of-wonders", "Do the shop trick for the 2nd Wisp above (start and cancel an Ancient of Wonders while the last Wisp is queued). Send this Wisp to the Tavern."],
      ["11/10", "ne-moon-well", "Build a Moon Well once you have enough lumber."],
      ["11/20", "ne-wisp", "Build a Wisp which goes to lumber."],
      ["12/20", "nt-firelord", "Train the Firelord at the Tavern. Uproot the Tree of Life and eat a tree near the expo so it survives the creep damage."],
      ["17/20", "ne-moon-well", "Build the 2nd Moon Well once the lumber is reached."],
      ["17/20", "nt-creep", "Summon Lava Spawns to help you creep the expansion camp."],
      ["17/20", "ne-archer", "Once the Ancient of War finishes, build an Archer."],
      ["19/20", "ne-wisp", "Build 2 Wisps which go to lumber."],
      ["20/30", "ne-archer", "Build an Archer, build a Wisp, and move one Wisp to the expo (for defence and gold mining)."],
      ["23/30", "nt-expansion", "Around now you have 5 gold Wisps, 11 wood Wisps, 1 hero, two Lava Spawns, one Archer and the expo creep finished (3:16 game marker)."],
      ["23/40", "ne-archer", "Build an Archer (or even two if being pressured)."],
      ["25/40", "ne-tree-of-ages", "Tech to tier 2 and move 3-4 lumber Wisps from your main to the expo gold mine, building Wisps at the expo."],
      ["26/40", "ne-wisp", "Build an Archer and keep building Wisps to fill the mine and replace lumber Wisps (5-7 depending on scouts and detonates lost)."],
      ["30/40", "ne-ancient-of-wonders", "Build an Ancient of Wonders and a Moon Well."],
      ["39/50", "nt-tavern", "Get a 2nd hero (Naga or Panda are great choices). Keep building Archers, up to 7."],
      ["41/50", "ne-tree-of-eternity", "Tech tier 3, build a Hunter's Hall and Archers until you are right below 50 food."],
      ["47/50", "ne-ancient-of-lore", "Once the Hunter's Hall finishes, build 2 Ancients of Lore."],
      ["50/50", "nt-upgrade", "Tier 3 finishes: get Marksmanship."],
      ["50/50", "ne-mountain-giant", "Break upkeep with a Shredder if needed, a Priestess of the Moon and 2 Mountain Giants."],
    ],
  },
  {
    slug: "1-aow-fast-hunts-tech",
    title: "1 AoW Fast Hunts Tech",
    guideId: "guide-1511",
    vsRace: "orc",
    difficulty: "beginner",
    tags: ["huntresses", "keeper of the grove", "beginner"],
    summary:
      "A beginner friendly Night Elf build: Keeper of the Grove, Hunter's Hall and a single Ancient of War into Huntresses, tech at 23 food with Ultravision. Sturdy units that forgive weak micro.",
    description: [
      "This build is good for beginners who are still learning the game and not confident in their micro, since Huntresses are much beefier than Archers. It sees most use against Orcs going Blademaster and Grunts, and is fine against Ghouls, Footmen or small numbers of Archers or Fiends. At higher levels players usually go Huntresses for early aggression instead.",
      "Easy. You also see variants with an early expansion and mass tier 1 units with a Keeper in Night Elf versus Orc.",
    ],
    steps: [
      ["5/10", "ne-altar", "Send 4 of your 5 Wisps to the gold mine. The 5th Wisp builds an Altar, then scouts the enemy once the Altar is up."],
      ["5/10", "ne-wisp", "Queue 2 Wisps."],
      ["6/10", "ne-moon-well", "Your 1st Wisp produced builds a Moon Well, then shift-click it onto a tree so it harvests lumber after."],
      ["7/10", "nt-gold", "Rally your 2nd produced Wisp to the gold mine so you have 5/5 on gold."],
      ["7/10", "ne-wisp", "Queue as many Wisps as you can (8 more, for 10 on wood including the scout). Rally all of them to harvest wood."],
      ["10/20", "ne-keeper-of-the-grove", "Start training your first hero (Keeper of the Grove is good with Huntresses for lockdown)."],
      ["18/20", "ne-hunters-hall", "When you have 160 wood build a Hunter's Hall and an Ancient of War."],
      ["17/20", "ne-moon-well", "When you have 40 wood get a 2nd Moon Well."],
      ["20/30", "ne-huntress", "Train a Huntress."],
      ["23/30", "ne-tree-of-ages", "Start the tech to tier 2 as soon as possible."],
      ["23/30", "ne-moon-well", "At 40 wood build Moon Well #3."],
      ["23/30", "nt-upgrade", "Research Ultravision as soon as possible."],
      ["23/30", "ne-huntress", "Continue Huntress production. By tier 2 you should have 4-5 Huntresses."],
    ],
  },
  {
    slug: "naga-archer-talon-push",
    title: "1st Hero and Naga Archer/DotT Push",
    guideId: "guide-1528",
    vsRace: "any",
    difficulty: "beginner",
    tags: ["timing push", "archers", "naga", "druids of the talon"],
    summary:
      "A timing push to end the game around 8-9 minutes: eleven Archers with Improved Bows, a Naga Sea Witch second and two Druids of the Talon casting Faerie Fire, plus Wisps to detonate.",
    description: [
      "A strong timing push to hopefully end the game close to the 8-9 minute mark. The idea is a decent number of Archers with 2 Druids of the Talon in the back casting Faerie Fire to reduce armour and give vision. The Naga second brings damage, slow with Frost Arrow and, at level 2, Chain Lightning as a finisher. Buy Heal and Protection Scrolls on the way.",
      "Easy, though you need to know how to Ancient of War creep. Ideally your first hero is level 3 when you push.",
    ],
    steps: [
      ["5/10", "ne-altar", "4 Wisps to the mine and 1 Wisp builds an Altar. Shift-click so that Wisp scouts when the Altar is finished."],
      ["5/10", "ne-wisp", "Queue your 1st Wisp. Take a Wisp from the gold mine to where you want the Ancient of War, ideally in position to creep."],
      ["7/10", "ne-ancient-of-war", "The 1st Wisp created builds a Moon Well, then make your Ancient of War with the Wisp from the gold mine."],
      ["6/10", "nt-gold", "Queue Wisps #2 and #3 and rally both to the gold mine so you have 5 on gold."],
      ["7/10", "ne-wisp", "Continue Wisp production up to 20/20 food (9 on wood and 5 on gold in total)."],
      ["9/20", "ne-demon-hunter", "Start training your hero."],
      ["15/20", "ne-archer", "Queue your 1st Archer."],
      ["18/20", "ne-moon-well", "As soon as you have 40 wood build your 2nd Moon Well."],
      ["19/20", "nt-creep", "Start Ancient of War creeping with your first Archer."],
      ["20/20", "ne-ancient-of-wonders", "Your 9th wood Wisp is stuck in queue: start an Ancient of Wonders with a wood Wisp to drop to 19/20, then cancel it once the Wisp starts training."],
      ["21/30", "ne-tree-of-ages", "Tech to tier 2 at your Tree of Life and then queue your 2nd Archer."],
      ["23/30", "ne-archer", "Queue your 3rd Archer."],
      ["25/30", "ne-moon-well", "Build your third Moon Well and queue your 4th and 5th Archers when you can."],
      ["29/30", "ne-ancient-of-wonders", "Build an Ancient of Wonders and queue a 6th Archer."],
      ["30/40", "ne-archer", "Queue a 7th Archer."],
      ["32/40", "nt-naga-sea-witch", "Buy the Naga from the Tavern as soon as the tier 2 tech finishes and start Improved Bows at the Ancient of War."],
      ["37/40", "ne-ancient-of-wind", "Get your 4th Moon Well, make an Ancient of Wind and buy a Staff of Preservation at your shop."],
      ["36/40", "ne-archer", "When Improved Bows completes, pump Archers until you reach roughly 11."],
      ["?/50", "ne-druid-of-the-talon", "When the Ancient of Wind finishes queue 2 Druids of the Talon."],
      ["?/50", "nt-attack", "With hero 1 plus Naga, 11-12 Archers and 2 Talons, push. Bring 3-5 Wisps to detonate, and 1-2 Heal and Protection Scrolls."],
    ],
  },
  {
    slug: "tavern-hero-first",
    title: "Tavern Hero First",
    guideId: "guide-2912",
    vsRace: "any",
    difficulty: "beginner",
    tags: ["tavern hero", "archers", "lazy build"],
    summary:
      "The simple way to open with a Tavern hero as Night Elf: Ancient of War and two Moon Wells before the Altar, three Archers, pick up the neutral hero at 20 food and tech at 25 during the first creep.",
    description: [
      "Night Elf is by far the most common race to pick a Tavern hero first. Sometimes it is simply fun; sometimes it is one of the strongest things to do on a map against a certain race, like Beastmaster first against Human on Last Refuge. This is a general build to get a Tavern hero first, not a discussion of what to do with each hero.",
      "This is a lazy build: not the most efficient, but the simplest and most straightforward. Easy, as long as you can Ancient of War creep a medium camp, which is what you normally take first.",
    ],
    steps: [
      ["5/10", "ne-wisp", "4 Wisps to the gold mine, 1 to harvest lumber, queue 3 Wisps at the Tree of Life."],
      ["6/10", "ne-ancient-of-war", "The 1st Wisp from the Tree of Life becomes your Ancient of War, so rally it to where you want the Ancient."],
      ["7/10", "ne-ancient-of-war", "Build the Ancient of War with the 1st Wisp, then rally the Tree of Life to where you want the 1st Moon Well."],
      ["7/10", "ne-moon-well", "Build the 1st Moon Well with the 2nd Wisp, then rally the Tree of Life to the gold mine so the 3rd Wisp saturates it (5/5)."],
      ["7/10", "ne-wisp", "Queue 3 more Wisps. Shift-click the Moon Well Wisp to build another Moon Well right after the first."],
      ["8/10", "nt-lumber", "The next Wisp (3rd made) goes to harvest lumber, so rally the Tree of Life accordingly."],
      ["9/10", "ne-altar", "The next Wisp (4th made) builds your Altar, so rally it where you want it."],
      ["10/10", "nt-lumber", "The rest of your produced Wisps go to harvest lumber."],
      ["10/20", "ne-archer", "The 1st Moon Well and Ancient of War finish around the same time. Instantly start training your 1st Archer."],
      ["12/20", "nt-scout", "Queue another lumber Wisp and use one of your lumber Wisps to scout the opponent."],
      ["13/20", "ne-wisp", "Queue another lumber Wisp."],
      ["14/20", "ne-archer", "Queue a 2nd Archer and move another lumber Wisp to a tree close to the Tavern."],
      ["16/20", "ne-wisp", "Queue another lumber Wisp."],
      ["17/20", "ne-archer", "Queue a 3rd Archer and your final lumber Wisp as soon as you can."],
      ["20/30", "nt-tavern", "Your Altar and 2nd Moon Well finish around the same time. Have your Wisp in range of the Tavern and pick up your neutral hero."],
      ["25/30", "ne-wisp", "25 is the food count you want. If you lost your scout Wisp, rebuild it quickly before tech. You want 9 Wisps on wood."],
      ["25/30", "ne-tree-of-ages", "Tech as soon as you have enough lumber, which should be during your first creep (usually an Ancient of War creep of a bigger camp)."],
    ],
  },
  {
    slug: "24-food-proxy-expo",
    title: "24 Food Proxy Expo",
    guideId: "guide-3437",
    vsRace: "undead",
    difficulty: "intermediate",
    tags: ["proxy expansion", "archers", "dryads", "two base"],
    summary:
      "Trade a little early power for a two-base economy: tech at 24 food and plant a proxy Tree of Life the opponent may never scout, walk it to the expansion, then two Ancients of Lore into Dryads.",
    description: [
      "This build is seen mostly against Undead but has situational viability elsewhere. The idea is to sacrifice a little early power to establish a two-base economy; once it is running you can pump units and upgrades. Because the expansion is a proxy, the opponent may not scout it, which is an even bigger advantage.",
      "Medium difficulty: requires Ancient of War creeping and knowing where to place proxy expansions.",
    ],
    steps: [
      ["5/10", "ne-altar", "Send 4 Wisps to the gold mine. 1 Wisp builds the Altar, then shift-click it to scout the enemy base. Queue Wisps #1 and #2."],
      ["6/10", "ne-ancient-of-war", "Pull a Wisp from gold to build the Ancient of War near the 1st creep camp. Your first built Wisp builds Moon Well #1, then shift-click it to lumber."],
      ["6/10", "nt-gold", "Queue Wisp #3. Rally Wisps #2 and #3 to the gold mine to have 5/5 on gold."],
      ["7/10", "ne-wisp", "Queue Wisp #4 and rally to wood. Continue production until 10 wood Wisps in total."],
      ["9/20", "ne-demon-hunter", "Start training your first hero."],
      ["15/20", "ne-archer", "Queue Archer #1."],
      ["18/20", "ne-moon-well", "As soon as you have 40 wood build Moon Well #2."],
      ["19/20", "nt-creep", "Start Ancient of War creeping."],
      ["20/20", "ne-ancient-of-wonders", "Shop trick for 21/20: start building a shop, queue a Wisp at your Tree of Life, then immediately cancel the shop."],
      ["22/30", "ne-archer", "Queue Archer #2."],
      ["24/30", "ne-wisp", "You should have 10 wood Wisps."],
      ["24/30", "ne-tree-of-ages", "Tech to tier 2."],
      ["24/30", "ne-tree-of-life", "At 340 gold and 185 wood build a Tree of Life in a proxy location."],
      ["23/30", "ne-archer", "Queue Archer #3."],
      ["25/30", "ne-hunters-hall", "Build Moon Well #3 and a Hunter's Hall."],
      ["25/30", "ne-archer", "Queue Archer #4 (when this Archer finishes, use the Ancient of War to continue creeping)."],
      ["27/40", "nt-upgrade", "Upgrade Ultravision as soon as the Hunter's Hall finishes."],
      ["27/40", "nt-tavern", "Your tier 2 tech should be done. Start your 2nd hero."],
      ["32/40", "ne-wisp", "Queue a Wisp."],
      ["33/50", "nt-expansion", "The proxy Tree of Life finishes: walk it to your expansion and creep the expansion when it arrives."],
      ["33/50", "ne-ancient-of-lore", "Build an Ancient of Lore."],
      ["32/50", "ne-tree-of-eternity", "Here you can vary the build: follow along, or tech to tier 3 and then add a 2nd Ancient of Lore."],
      ["32/50", "ne-ancient-of-lore", "Build Ancient of Lore #2, then build a shop."],
      ["30/50", "ne-dryad", "Once the Tree of Life roots at your expo, train 5 Wisps out of it to fill the mine. When the Ancients of Lore finish begin training Dryads."],
      ["43/50", "ne-moon-well", "Build Moon Well #4."],
    ],
  },
  {
    slug: "mass-talons-vs-orc",
    title: "Mass Talons vs Orc",
    guideId: "guide-6304",
    vsRace: "orc",
    difficulty: "advanced",
    tags: ["druids of the talon", "beastmaster", "tinker", "harass", "tier 3"],
    summary:
      "The build that ran Night Elf versus Orc for years: Demon Hunter and Archers into a straight tier 3 tech, two Ancients of Wind pumping Talons, Beastmaster second, Tinker third, then push.",
    description: [
      "Mass Talons versus Orc ran the Night Elf versus Orc meta for years, especially during the lull of patch 1.26. This strategy takes practice and understanding of the execution needed to make it work; the guide gives context to the build order, its strengths and weaknesses, and how to read your opponent. Watch the replays linked in it and practise.",
      "Cyclone is the whole point: keep the Blademaster in the air at all times, then Grunts and Raiders. Do not cyclone Spirit Walkers, they can only be held for a short time.",
    ],
    steps: [
      ["5/10", "ne-altar", "Put 4 of the starting Wisps on gold and have the 5th Wisp build an Altar."],
      ["5/10", "ne-wisp", "Build your 1st Wisp."],
      ["6/10", "ne-ancient-of-war", "Take a Wisp from your gold mine when the 1st queued Wisp is 2/3 done and build an Ancient of War, ideally in position to creep."],
      ["6/10", "ne-wisp", "Queue your 2nd Wisp."],
      ["6/10", "ne-moon-well", "The 1st Wisp created builds a Moon Well."],
      ["7/10", "nt-gold", "Queue your 3rd Wisp. Your 2nd and 3rd Wisps go to gold for 5/5. All future Wisps go to wood."],
      ["8/10", "ne-wisp", "Queue your 4th Wisp."],
      ["9/10", "nt-lumber", "The Wisps that built the Moon Well and Altar go to wood."],
      ["9/10", "ne-demon-hunter", "Build your first hero (usually Demon Hunter, Keeper is viable too). Continue Wisps until you have 9 on wood in total."],
      ["14/20", "nt-scout", "Send your next Wisp out of the Tree of Life (right after queuing a hero) to scout the opponent."],
      ["15/20", "ne-archer", "Build an Archer."],
      ["18/20", "ne-moon-well", "Build a Moon Well once you hit 40 wood."],
      ["19/20", "nt-creep", "When the Archer completes, begin the Ancient of War creep."],
      ["20/20", "ne-ancient-of-wonders", "Your 9th wood Wisp is stuck in queue: start an Ancient of Wonders with a wood Wisp to drop to 19/20, then cancel it once the Wisp starts training."],
      ["21/30", "ne-tree-of-ages", "Build a 2nd Archer. Tech to tier 2 (you should have 5 on gold, 9 on wood, 2 Archers and 1 hero)."],
      ["23/30", "ne-archer", "Build a 3rd Archer."],
      ["25/30", "ne-moon-well", "Build a Moon Well when you have enough lumber."],
      ["25/30", "ne-archer", "Build a 4th Archer (not needed, but it helps with creeping and any early pressure)."],
      ["27/30", "ne-ancient-of-wonders", "You can build an early shop to close off your base and protect your future Ancients of Wind from harass."],
      ["27/40", "ne-tree-of-eternity", "When tier 2 finishes, tech to tier 3 immediately."],
      ["27/40", "ne-ancient-of-wind", "Build 2 Ancients of Wind in a safe position inside your base."],
      ["25/40", "ne-moon-well", "Build a Moon Well."],
      ["25/40", "nt-beastmaster", "Buy a 2nd hero (most commonly Beastmaster skilling Quillbeast; see the guide for more)."],
      ["30/40", "nt-attack", "Summon a Quillbeast right after buying the Beastmaster and go to the Orc base to cancel tier 2 buildings or kill burrows. A TP for a building kill is worth it."],
      ["30/40", "ne-druid-of-the-talon", "Once the Ancients of Wind finish, research Adept training and make one Druid of the Talon. Creep your heroes."],
      ["32/40", "ne-druid-of-the-talon", "Continue to build Talons until tier 3 finishes."],
      ["40/50", "nt-upgrade", "Tier 3 finishes: research Master training. Buy the push items (Orb of Venom, Staff of Preservation, TP, invulnerability potion, Heal Scroll) and head out."],
      ["42/50", "nt-goblin-tinker", "Pick up a Tinker on the way to the opponent's base. Train a Pocket Factory to damage buildings and deal damage over time in the fight."],
      ["47/50", "nt-attack", "Fight the Orc. Keep the Blademaster in the air at all times, then Grunts and Raiders. Do not cyclone Spirit Walkers."],
    ],
  },
];
