/**
 * Orc build orders transcribed from the Warcraft-gym.com build cards that sit
 * inside the Learn guides. Steps: [supply, icon key, instruction].
 * See to-ndjson.mjs for the import.
 */
export const BUILDS = [
  {
    slug: "farseer-headhunter-2-burrow-tech",
    title: "Farseer Headhunter 2 Burrow Tech",
    guideId: "guide-1023",
    vsRace: "any",
    difficulty: "beginner",
    tags: ["headhunters", "standard", "farseer"],
    summary:
      "The most versatile Orc opening: Farseer, six Headhunters and two burrows before tech, with harass or creeping depending on the matchup.",
    description: [
      "The Farseer Headhunter 2 Burrow Tech is the most versatile opening Orc players have. It can work against every race and offers transitions into multiple strong mid and late game strategies, which also makes it a good choice versus opponents playing random.",
      "Strong early pressure, fast and safe creeping with wolves tanking, and an army that is easy to micro. The trade-off is a slow tech: your second hero arrives a bit later than with other openers, and Headhunters are vulnerable in the midgame until tier 2 units or the Berserker upgrade arrive.",
    ],
    steps: [
      ["5/11", "or-peon", "Queue 3 peons in your Great Hall."],
      ["6/11", "or-altar", "Send 4 of your starting peons to gold, the 5th builds an Altar."],
      ["7/11", "or-burrow", "The 1st peon produced builds a burrow."],
      ["8/11", "or-peon", "The 2nd peon produced fills up the gold mine to 5/5. Queue another (4th) peon."],
      ["9/11", "or-war-mill", "The 3rd peon produced builds a War Mill. Queue another (5th) peon."],
      ["10/11", "nt-lumber", "The 4th peon produced gathers lumber. Queue another (6th) peon."],
      ["10/21", "or-far-seer", "Build a Farseer. Peons that built the Altar and burrow gather lumber."],
      ["16/21", "or-barracks", "The 5th produced peon builds a Barracks. Queue another (7th) peon."],
      ["17/21", "nt-lumber", "The 6th and 7th produced peons gather lumber. Stop peon production now."],
      ["17/21", "or-burrow", "Build a second burrow."],
      ["17/21", "or-far-seer", "Skill Spirit Wolves and send the Farseer towards the opponent to harass (vs NE, UD or HU) or to creep (vs Orc)."],
      ["17/21", "or-headhunter", "Queue 2 Headhunters as soon as the Barracks finishes."],
      ["21/31", "or-stronghold", "Upgrade your Great Hall to a Stronghold."],
      ["21/31", "or-headhunter", "Keep Headhunter production going until you have six of them."],
      ["27/31", "or-burrow", "Build a 3rd burrow or a Voodoo Lounge (if your Farseer is low on health you might want to build the Lounge first)."],
      ["29/31", "or-voodoo-lounge", "Build a Voodoo Lounge or a third burrow (the one you did not build previously)."],
      ["34/41", "or-tauren-chieftain", "As soon as tier 2 finishes, start your second hero (most common is the Tauren Chieftain)."],
      ["34/41", "nt-upgrade", "Optional: if a lot of your Headhunters are hurt get the Troll Regeneration upgrade, or get it later."],
      ["34/41", "or-spirit-lodge", "Build up to two tier 2 buildings depending on what you want your end game composition to be."],
    ],
  },
  {
    slug: "farseer-1-grunt-into-headhunters",
    title: "Farseer 1 Grunt into Headhunters",
    guideId: "guide-1026",
    vsRace: "orc",
    difficulty: "beginner",
    tags: ["headhunters", "grunt", "farseer", "mirror"],
    summary:
      "The 2 Burrow Headhunter build with one Grunt first for extra damage and tankiness while creeping. Mostly seen in the Orc mirror and on maps with tougher early camps.",
    description: [
      "This is a variation of the 2 Burrow Headhunter build that adds one Grunt before building any Headhunters. The added Grunt gives some extra damage and tankiness for early creeping. The build is almost exclusively seen on maps where the Grunt is needed to creep and is typically seen in Orc mirror matches. You also sometimes see it on Amazonia versus Human, when the Orc wants to do the Lightning Shield creep first instead of harassing right away.",
      "The Grunt takes up 3 supply and Headhunters only 2, so you make up for it by having one less lumber peon.",
    ],
    steps: [
      ["5/11", "or-peon", "Queue 3 peons in your Great Hall."],
      ["6/11", "or-altar", "Send 4 of your starting peons to gold, the 5th builds an Altar."],
      ["7/11", "or-burrow", "The 1st peon produced builds a burrow."],
      ["8/11", "or-barracks", "The 2nd peon produced builds a Barracks. Queue another (4th) peon."],
      ["9/11", "nt-gold", "The 3rd peon produced fills up the gold mine to 5/5."],
      ["9/11", "or-war-mill", "The 4th peon produced builds a War Mill."],
      ["9/21", "or-far-seer", "Build a Farseer. Peons that built the Altar and burrow gather lumber."],
      ["14/21", "or-peon", "Queue another (5th) peon."],
      ["15/21", "nt-lumber", "The fifth peon produced goes to lumber."],
      ["15/21", "or-grunt", "Build a Grunt."],
      ["18/21", "or-burrow", "Pull a peon from wood and build a second burrow."],
      ["18/21", "or-peon", "Build a 6th peon and have it mine lumber."],
      ["19/21", "nt-creep", "Skill Spirit Wolves and send the Farseer and the Grunt to your first creep camp."],
      ["19/21", "or-headhunter", "Build a Headhunter."],
      ["21/31", "or-headhunter", "Build a second Headhunter."],
      ["23/31", "or-stronghold", "Upgrade your Great Hall to a Stronghold."],
      ["23/31", "or-headhunter", "Keep Headhunter production going until you have six of them."],
      ["29/31", "or-burrow", "Build a third burrow or a Voodoo Lounge (if your Farseer is low on health you might want to build the Lounge first)."],
      ["31/31", "or-voodoo-lounge", "Build a Voodoo Lounge or a third burrow (the one you did not build previously)."],
      ["31/41", "or-shadow-hunter", "As soon as tier 2 finishes, start your second hero (most common is the Shadow Hunter)."],
      ["36/41", "nt-upgrade", "Optional: if a lot of your Headhunters are hurt get the Troll Regeneration upgrade."],
      ["36/41", "or-spirit-lodge", "Build up to two tier 2 buildings."],
    ],
  },
  {
    slug: "farseer-fast-tech-without-barracks",
    title: "Farseer Fast Tech without Barracks",
    guideId: "guide-1106",
    vsRace: "human",
    difficulty: "intermediate",
    tags: ["fast tech", "farseer", "harass"],
    summary:
      "The fastest standard Orc tech: Farseer harass while you skip the Barracks and go straight to Stronghold at 17 supply. Strongest against Human.",
    description: [
      "This is the fastest standard tech in the game. It used to be the go-to strategy versus Human until Headhunters got popular, and it is still very strong in the matchup. You rarely see this build in other matchups besides Human, and if you do it is mostly to go into mass Wind Riders later on.",
      "Intermediate difficulty: you need to multitask creeping with your second hero while harassing with the first.",
    ],
    steps: [
      ["5/11", "or-peon", "Queue 3 peons in your Great Hall."],
      ["6/11", "or-altar", "Send 4 of your starting peons to gold, the 5th builds an Altar."],
      ["7/11", "or-burrow", "The 1st peon produced builds a burrow. Queue another (4th) peon."],
      ["8/11", "nt-lumber", "The 2nd peon produced gathers lumber."],
      ["9/11", "nt-gold", "The 3rd peon produced fills up the gold mine to 5/5."],
      ["9/11", "or-peon", "Queue 3 more peons (5th, 6th and 7th)."],
      ["10/11", "nt-lumber", "The 4th produced peon gathers lumber."],
      ["10/21", "or-far-seer", "Build a Farseer. Peons that built the Altar and burrow gather lumber."],
      ["17/21", "nt-lumber", "The fifth, sixth and seventh produced peons gather lumber."],
      ["17/21", "or-stronghold", "Upgrade your Great Hall to a Stronghold as soon as the seventh peon is produced."],
      ["17/21", "or-barracks", "Build a Barracks as soon as you hit 50 lumber."],
      ["17/21", "or-far-seer", "Skill Spirit Wolves and send the Farseer towards the opponent."],
      ["17/21", "or-burrow", "Build a second burrow as soon as you hit 40 lumber."],
      ["17/21", "nt-attack", "Try to harass the enemy creeping and economy with your Farseer."],
      ["17/31", "or-grunt", "Build a Grunt."],
      ["20/31", "or-voodoo-lounge", "Build a Voodoo Lounge."],
      ["20/31", "or-grunt", "Build another Grunt."],
      ["23/31", "or-tauren-chieftain", "As soon as tier 2 finishes start your second hero (Tauren Chieftain most of the time)."],
      ["28/31", "or-spirit-lodge", "Build a Spirit Lodge and a Beastiary."],
      ["28/31", "or-burrow", "Build a third burrow."],
      ["", "nt-upgrade", "Get a third Grunt now if you need it for creeping, and Brute Strength as soon as you have the lumber after starting your tier 2 buildings."],
    ],
  },
  {
    slug: "1-burrow-barracks-and-shop-before-tech",
    title: "1 Burrow, Barracks and Shop before Tech",
    guideId: "guide-1120",
    vsRace: "any",
    difficulty: "intermediate",
    tags: ["standard", "grunts", "one burrow"],
    summary:
      "The standard Orc opener: one burrow, Barracks and Voodoo Lounge before a 20 supply Stronghold, three Grunts and a quick second hero. Flexible into any tier 2 plan.",
    description: [
      "This opening is one of the most standard and versatile openings for Orc. It allows you to transition into multiple different builds at tier 2 and also get a relatively quick second hero. It does not have the strength of a Headhunter build early on, but it lets you play multiple different first and second heroes.",
      "An ok build for newer players, but not as beginner-friendly as a 2 burrow tech since it is not as easy or safe. Regardless of the matchup, the goal is always to reach 50 supply of your chosen composition with level 3 on both heroes.",
    ],
    steps: [
      ["5/11", "or-altar", "Send 4 of your 5 peons into the gold mine and the 5th builds an Altar of Storms."],
      ["5/11", "or-peon", "Queue up 2 peons in the Great Hall (your first built peon goes to gold)."],
      ["6/11", "or-burrow", "When your 1st queued peon is about 60-70% done, take 1 peon out of the gold mine and build a burrow."],
      ["7/11", "or-peon", "Queue up another (3rd) peon."],
      ["8/11", "or-barracks", "Take the 2nd built peon when it is created and build a Barracks."],
      ["8/11", "or-peon", "Queue up another (4th) peon."],
      ["9/11", "nt-gold", "Your 3rd created peon goes to gold; you now have 5 peons on gold."],
      ["9/11", "nt-lumber", "Never more than 5 peons on gold. Every other peon goes to lumber, and peons that build go to lumber after."],
      ["9/11", "or-peon", "Queue up another (5th) peon."],
      ["10/21", "or-blademaster", "When both your Altar and burrow finish, train your first hero."],
      ["15/21", "or-peon", "Queue up another (6th) peon."],
      ["16/21", "or-voodoo-lounge", "At 30 lumber a lumber peon builds a Voodoo Lounge, then shift-click it back to lumber."],
      ["16/21", "or-grunt", "As soon as your Barracks finishes, train 1 Grunt. It is correct that there is a gap in peon production."],
      ["19/21", "or-peon", "Queue up your last (7th) peon."],
      ["20/21", "or-stronghold", "As soon as you have 190 lumber, upgrade your Great Hall to a Stronghold."],
      ["20/21", "nt-creep", "Take your Grunt and hero and creep one green camp before coming back to the shop to buy items."],
      ["20/21", "or-burrow", "When you have 40 lumber, take a lumber peon and build your 2nd burrow."],
      ["20/21", "or-burrow", "When you have enough resources, build your 3rd burrow."],
      ["20/31", "or-grunt", "Train your second Grunt."],
      ["23/31", "or-grunt", "Train your third Grunt. Depending on your end game composition you may not make more Grunts except to replace dead ones."],
      ["", "or-stronghold", "Once your tier 2 upgrade finishes, transition into one of the tier 2 builds from the guide."],
    ],
  },
  {
    slug: "two-burrow-tech-with-grunts",
    title: "Two Burrow Tech with Grunts",
    guideId: "guide-1332",
    vsRace: "any",
    difficulty: "beginner",
    tags: ["grunts", "two burrow", "safe"],
    summary:
      "The safe Orc opener: second burrow and two Grunts before tech at 23 supply. Slower than one burrow tech but far harder to punish. Common in the mirror and vs Night Elf.",
    description: [
      "The two burrow tech with Grunts is a variation of the one burrow tech where you build your second burrow before teching instead of afterwards. It is most commonly used in the mirror and versus Night Elf. The tech is slower, but your second burrow is far less exposed to early aggression, and making four Grunts during the tech makes early harass and tower rush attempts much easier to deal with.",
      "Easier to get into and less punishing than one burrow teching, but it gets harder to execute the stronger your opponents get: the slow tech puts you behind by default, so you have to snowball off your creeping.",
    ],
    steps: [
      ["5/10", "or-peon", "Queue 2 peons in your Great Hall."],
      ["6/10", "or-altar", "Send 4 of your starting peons to mine gold, the 5th starting peon starts an Altar."],
      ["7/11", "or-burrow", "Your 1st peon produced builds your first burrow, then harvests lumber."],
      ["8/11", "or-barracks", "The 2nd peon produced builds your Barracks. Queue peons until 11/11 from here on."],
      ["9/11", "nt-gold", "The 3rd peon produced saturates your gold mine (5/5)."],
      ["10/11", "nt-lumber", "The 4th, 5th and 6th peons produced gather lumber."],
      ["10/11", "or-blademaster", "Train your hero of choice."],
      ["16/21", "or-burrow", "As soon as you hit 40 lumber, construct your second burrow."],
      ["16/21", "or-grunt", "When your Barracks finishes, train a Grunt."],
      ["19/21", "or-voodoo-lounge", "When you get 130 gold, build a Voodoo Lounge."],
      ["19/21", "or-peon", "When you get 80 gold, train your 7th peon and send it to lumber."],
      ["20/21", "nt-creep", "Start creeping with your hero and Grunt as soon as they finish training."],
      ["20/31", "or-grunt", "As soon as your 2nd burrow finishes, train your 2nd Grunt."],
      ["23/31", "or-stronghold", "Tech as soon as possible, right about when your 2nd Grunt finishes (around 2:50)."],
    ],
  },
  {
    slug: "no-barracks-shop-before-tech",
    title: "No Barracks Shop before Tech",
    guideId: "guide-1337",
    vsRace: "any",
    difficulty: "advanced",
    tags: ["fast tech", "blademaster", "harass", "niche"],
    summary:
      "A niche Orc fast tech: Voodoo Lounge instead of Barracks, Stronghold at 17 supply, hero out with items to harass immediately. For specific maps and matchups only.",
    description: [
      "This opening is a rather niche one for Orc. It is usually limited to specific map, matchup or build situations where it gives you a slight edge over its siblings, the No Barracks tech without shop and the 1 Burrow Barracks tech. Examples are Blademaster openings where you want to keep Healing Salves so you are not forced to abandon your harass early.",
      "The build order itself is not hard to execute, but the strategies it is used in are advanced and need a good read of the metagame and your opponent, so it is not recommended for beginners.",
    ],
    steps: [
      ["5/11", "or-altar", "Send 4 of your 5 peons to the gold mine and have the 5th peon build an Altar of Storms."],
      ["5/11", "or-peon", "Queue up 2 peons in the Great Hall (your first built peon goes to gold)."],
      ["6/11", "or-burrow", "When your 1st queued peon is about 60-70% done, take 1 peon out of your gold mine and build a burrow."],
      ["7/11", "or-peon", "Queue up another (3rd) peon."],
      ["8/11", "or-voodoo-lounge", "Take the 2nd built peon when it is created and build a Voodoo Lounge."],
      ["8/11", "or-peon", "Queue up another (4th) peon."],
      ["9/11", "nt-gold", "Your 3rd created peon goes to gold; you now have 5 peons on gold."],
      ["9/11", "nt-lumber", "Never more than 5 peons on gold. Every other peon goes to lumber, and peons that build go to lumber after."],
      ["9/11", "or-peon", "Queue up another (5th) peon."],
      ["10/21", "or-blademaster", "When both your Altar and burrow finish, train your first hero."],
      ["15/21", "or-peon", "Queue up another (6th) peon."],
      ["16/21", "or-peon", "Queue up your last (7th) peon."],
      ["17/21", "or-stronghold", "As soon as you have 190 lumber, upgrade your Great Hall to a Stronghold."],
      ["17/21", "nt-attack", "When your hero finishes, buy a speed scroll, a Healing Salve and a Potion of Clarity and move across the map. Sell the Town Portal if needed."],
      ["17/21", "or-burrow", "Take a lumber peon and build your 2nd burrow."],
      ["17/21", "or-barracks", "When you have the resources, build your Barracks. The 2nd burrow comes first so a counter-harass cannot supply block you."],
      ["17/31", "or-grunt", "As soon as your Barracks finishes, train a Grunt."],
      ["20/31", "or-grunt", "Train a second Grunt. Depending on your end game composition you may not make more Grunts except to replace dead ones."],
      ["", "or-stronghold", "Once your tier 2 upgrade finishes, transition into one of the tier 2 builds from the guide."],
    ],
  },
  {
    slug: "tauren-chieftain-headhunters",
    title: "Tauren Chieftain Headhunters",
    guideId: "guide-2929",
    vsRace: "any",
    difficulty: "beginner",
    tags: ["headhunters", "tauren chieftain", "team games"],
    summary:
      "Quick Headhunters with a slow Tauren Chieftain: Barracks before Altar, three Headhunters by the time the hero is out. Straightforward, strongest in team games.",
    description: [
      "Tauren Chieftain and Headhunters is an unconventional strategy in solo but it does see use, and it is most effective in team games (2v2, 4v4) because Headhunters provide military strength from early on and scale well through most of the game, especially with the tier 3 Berserker upgrade. The Chieftain's aura complements them nicely.",
      "With Headhunters you creep fast and cost-efficiently since you spend less gold on healing items than with Grunts. Get as many as possible as quickly as possible: they are weak in small numbers. Easy to execute, but the build has many weaknesses.",
    ],
    steps: [
      ["5/11", "or-peon", "Send all 5 peons to gold. Queue up 3 peons."],
      ["6/11", "or-burrow", "Your 1st peon created builds a burrow and is rallied to lumber after."],
      ["7/11", "or-war-mill", "Your 2nd peon created builds a War Mill. Queue up another peon."],
      ["8/11", "or-barracks", "Your 3rd peon created builds a Barracks. Queue up another peon."],
      ["9/11", "or-altar", "Your 4th peon created builds an Altar. All peons that build should be rallied to lumber after."],
      ["10/21", "or-peon", "Queue up another peon. The rest of the peons created go to lumber right away."],
      ["11/21", "or-peon", "Queue up another peon."],
      ["12/21", "or-burrow", "Build the 2nd burrow as soon as you have 40 wood, using the peon that just returned lumber."],
      ["12/21", "or-headhunter", "When the Barracks finishes build a Headhunter."],
      ["14/21", "or-tauren-chieftain", "Build your Tauren Chieftain when the Altar finishes (or plan for a Tavern hero). Queue a 2nd Headhunter."],
      ["21/21", "or-headhunter", "Queue a 3rd Headhunter."],
      ["23/31", "nt-creep", "With 2 Headhunters out and the Chieftain not yet done, you can start pulling a green camp to damage it."],
      ["23/31", "or-headhunter", "When the Chieftain comes out you should have 3 Headhunters and 7 wood peons."],
      ["23/31", "or-voodoo-lounge", "Choose: tech after the 3rd Headhunter to be quick, or build a shop first to be safe."],
      ["23/31", "or-tauren-chieftain", "Get Endurance Aura level 1 on the Chieftain to creep faster rather than pressuring early."],
      ["23/31", "or-stronghold", "Continue pumping Headhunters as you go to tier 2."],
      ["27/31", "nt-upgrade", "Get the Headhunter attack upgrade after several more Headhunters are out. It is cheap but strong."],
    ],
  },
  {
    slug: "tier-2-farseer-naga-push-vs-ne",
    title: "Tier 2 Farseer / Naga Push vs NE",
    guideId: "guide-7362",
    vsRace: "nightelf",
    difficulty: "intermediate",
    tags: ["timing push", "naga", "grunts", "farseer"],
    summary:
      "Grunts into a tier 2 timing: Farseer with wolves, Naga Sea Witch from the Tavern, Pillage and Brute Strength, then hit the Night Elf base with five Grunts before Bears or Dryads arrive.",
    author: "pierikara",
    authorDiscord: "pierikara",
    description: [
      "This build gives Orc another tool against Night Elf. Top players such as Grubby, Starbuck and Knoff have experimented with variations, some relying on Headhunters, but for mere mortals Grunts provide more stability during the push.",
      "Easier to get into than a one burrow tech and less punishing, but harder to execute when facing unusual Night Elf builds or hero choices. Scout with a wolf before your second camp, get a Voodoo Lounge up quickly if harassed, and do not get tempted into level 3 before the push: you risk being creepjacked or losing the Tavern.",
    ],
    steps: [
      ["5/10", "or-peon", "Queue 2 peons in your Great Hall."],
      ["6/10", "or-altar", "Send 4 of your starting peons to mine gold, the 5th starting peon starts an Altar."],
      ["7/11", "or-burrow", "1-2 seconds before your 1st peon is made, take one peon from the gold mine to build a burrow. The 1st peon produced starts mining gold."],
      ["8/11", "or-barracks", "The 2nd peon produced builds your Barracks. Queue peons until 11/11 from here on."],
      ["9/11", "nt-gold", "The 3rd peon produced saturates your gold mine (5/5)."],
      ["10/11", "nt-lumber", "All future peons produced are sent to gather lumber."],
      ["10/11", "or-far-seer", "Train your Farseer."],
      ["15/21", "or-burrow", "As soon as you hit 40 lumber, construct your second burrow with a lumber peon."],
      ["16/21", "or-grunt", "As soon as you have 200 gold, start training the 1st Grunt."],
      ["19/21", "or-peon", "When you get 75 gold, train your 7th peon (the last peon for this build)."],
      ["20/21", "nt-creep", "Start creeping with your hero and Grunt as soon as they have finished training."],
      ["20/31", "or-stronghold", "As soon as you have 190 lumber, start teching to Stronghold."],
      ["20/31", "or-grunt", "As soon as your 2nd burrow finishes, train your 2nd Grunt."],
      ["23/31", "or-voodoo-lounge", "As soon as you have the resources, build a Voodoo Lounge."],
      ["23/31", "or-grunt", "As soon as you have 200 gold, train your 3rd Grunt."],
      ["26/31", "or-burrow", "As soon as you have the resources, build your 3rd burrow."],
      ["26/31", "or-grunt", "As soon as you have 200 gold, train your 4th Grunt."],
      ["29/31", "or-far-seer", "Farseer should be level 2. Salve hurt Grunts, buy a speed scroll and Clarity Potion for a full-mana Farseer. Sell items you do not need."],
      ["29/41", "nt-naga-sea-witch", "Grunts to the Tavern, Farseer to the Goblin Merchant for Dust of Appearance. Hire the Naga Sea Witch."],
      ["34/41", "nt-upgrade", "On the way to the Night Elf base, research Pillage and Brute Strength."],
      ["34/41", "or-grunt", "When you have 200 gold, train your 5th Grunt."],
      ["37/41", "or-beastiary", "During the battle, build a Beastiary when you have the resources, then a War Mill, then the 4th burrow."],
      ["37/41", "or-raider", "When the Beastiary is built, train a Raider and queue the Ensnare research."],
    ],
  },
];
