/**
 * Undead build orders transcribed from the Warcraft-gym.com build cards that
 * sit inside the Learn guides. Steps: [supply, icon key, instruction].
 * See to-ndjson.mjs for the import.
 */
export const BUILDS = [
  {
    slug: "fast-death-knight-fiends",
    title: "Fast Death Knight Fiends",
    guideId: "guide-1029",
    vsRace: "any",
    difficulty: "beginner",
    tags: ["fiends", "death knight", "standard", "safe"],
    summary:
      "The standard safe Undead opening: Death Knight at 8 food, a Crypt Fiend before tech, quick tier 2 and tier 3 for statues and the orb. Six Fiends, two Statues, three heroes at 50.",
    description: [
      "Fast Death Knight into Fiends is one of the most standard and safe builds Undead has. It lets you tech quickly to tier 2 and tier 3, where Undead unlocks its power spikes: Obsidian Statues and the orb at tier 3.",
      "Not as basic as fast Fiends, but still an easier opening for newer players.",
    ],
    steps: [
      ["5/10", "ud-acolyte", "Send your 3 Acolytes to gold and the Ghoul to wood. Build 2 Acolytes."],
      ["6/10", "ud-ziggurat", "Use one of the first Acolytes to make a Ziggurat and an Altar."],
      ["7/10", "ud-crypt", "When the 5th Acolyte pops out build a Crypt, then have it mine gold."],
      ["7/10", "ud-acolyte", "Build a 6th Acolyte."],
      ["8/10", "ud-tomb-of-relics", "Build a Tomb of Relics with the 6th Acolyte. Kill a critter near the first camp you intend to creep, then scout your enemy."],
      ["8/20", "ud-death-knight", "Make your Death Knight."],
      ["13/20", "ud-graveyard", "Build a Graveyard."],
      ["13/20", "ud-ghoul", "Make 2 Ghouls."],
      ["17/20", "nt-creep", "When the Death Knight is summoned, buy a Rod of Necromancy right away, go to the critter body, use the rod and creep the camp."],
      ["17/20", "ud-crypt-fiend", "Build a Fiend as soon as you have the resources."],
      ["20/20", "ud-halls-of-the-dead", "Start upgrading your Necropolis."],
      ["20/20", "ud-ziggurat", "Build a Ziggurat."],
      ["20/30", "ud-crypt-fiend", "Build 2 Fiends."],
      ["25/30", "ud-lich", "Build a Lich or your second hero; your scouting Acolyte should be dead by now."],
      ["30/30", "ud-black-citadel", "Go tier 3 and build a Ziggurat and Slaughterhouse after. Or stay tier 2, build them first and tech at 39/40 after Fiends and Statues."],
      ["39/40", "ud-ziggurat", "Build a Ziggurat."],
      ["39/50", "nt-tavern", "Get a third hero and buy the orb at tier 3 as soon as possible."],
      ["44/50", "ud-obsidian-statue", "Build up to 50 food. You should have 6 Fiends, 2 Statues and 3 heroes."],
    ],
  },
  {
    slug: "fast-fiends-and-death-knight",
    title: "Fast Fiends and Death Knight",
    guideId: "guide-1096",
    vsRace: "orc",
    difficulty: "beginner",
    tags: ["fiends", "death knight", "beginner"],
    summary:
      "The build for every new Undead player: Crypt and Graveyard first, Death Knight and Fiend the moment the Ziggurat is up, four Fiends before tier 2. Safest and easiest Undead opening.",
    description: [
      "This is the build for all new Undead players. It is the safest and easiest to execute of all Undead strategies. Your very early game is weak, but you ramp up quickly with Fiends for a strong midgame presence. It has many weaknesses and is not recommended in many matchups at a higher level, where it is mostly seen in Undead versus Orc.",
      "Very good for new players.",
    ],
    steps: [
      ["5/10", "ud-acolyte", "Send your 3 Acolytes to gold and the Ghoul to wood. Build 1 Acolyte."],
      ["6/10", "ud-crypt", "Use one of the first Acolytes to make a Graveyard and a Crypt."],
      ["6/10", "ud-acolyte", "Queue a 2nd Acolyte."],
      ["7/10", "ud-altar", "Build an Altar as soon as you have the resources."],
      ["7/10", "ud-ziggurat", "Build a Ziggurat as soon as you can."],
      ["7/10", "ud-ghoul", "Build a Ghoul."],
      ["9/10", "ud-tomb-of-relics", "Build a Tomb of Relics."],
      ["9/10", "ud-death-knight", "Build a Death Knight and a Fiend when the Ziggurat is finished."],
      ["17/20", "ud-ziggurat", "Build a 2nd Ziggurat."],
      ["17/20", "ud-crypt-fiend", "Queue a 2nd Fiend as soon as possible."],
      ["20/30", "nt-creep", "When the Death Knight pops out, buy a Rod of Necromancy, use it on the Graveyard and creep a camp with skeletons, Fiend and DK."],
      ["20/30", "ud-crypt-fiend", "Build a 3rd Fiend."],
      ["23/30", "ud-halls-of-the-dead", "Upgrade the Necropolis."],
      ["23/30", "ud-ghoul", "Build a Ghoul and rally it to wood."],
      ["25/30", "ud-crypt-fiend", "Build a 4th Fiend."],
      ["28/30", "ud-ziggurat", "Get a 3rd Ziggurat."],
      ["28/40", "ud-lich", "Get a 2nd hero (Lich or Dark Ranger depending on the enemy)."],
      ["33/40", "ud-black-citadel", "Either tech straight to Black Citadel or stay tier 2 and build your Slaughterhouse before starting the tech."],
      ["33/40", "ud-slaughterhouse", "Do whichever you did not do in the prior step."],
      ["33/40", "ud-ziggurat", "Get a 4th Ziggurat. Get 2 Statues, Fiends and the Burrow upgrade. You may need a Temple of the Damned during or early at tier 3."],
      ["?/50", "nt-tavern", "At tier 3 buy an Orb of Corruption for the Lich and get a third hero."],
      ["?/50", "nt-upgrade", "Get the Destroyer upgrade. Decide if you need Abominations and Disease Cloud, or a Temple of the Damned for Banshees."],
    ],
  },
  {
    slug: "quick-1-ziggurat-tech-into-gargoyles",
    title: "Quick 1 Ziggurat Tech into Gargoyles",
    guideId: "guide-1127",
    vsRace: "nightelf",
    difficulty: "intermediate",
    tags: ["gargoyles", "harass", "pocket strategy"],
    summary:
      "A pocket strategy for Night Elf only: Death Knight harasses the wood line while you tech on one Ziggurat, then Gargoyles from two Crypts the moment tier 2 lands.",
    description: [
      "This build is a pocket strategy to be used only versus Night Elf; it is not effective against any other race. The point is to disrupt the Night Elf wood economy as soon as possible, first with the Death Knight and then with quick Gargoyles. It also allows a later transition into the late game Undead air armies or a timing attack.",
      "Intermediate, as it involves decision making and therefore experience. It has many holes and can be countered by a prepared Night Elf.",
    ],
    steps: [
      ["5/10", "ud-acolyte", "Send your 3 Acolytes to gold and the Ghoul to wood. Build 2 Acolytes."],
      ["6/10", "ud-ziggurat", "Use one of the first Acolytes to make a Ziggurat and an Altar."],
      ["7/10", "ud-crypt", "When the 5th Acolyte pops out build a Crypt, then have it mine gold."],
      ["7/10", "ud-acolyte", "Build a 6th Acolyte."],
      ["8/10", "ud-tomb-of-relics", "Build a Tomb of Relics with the 6th Acolyte when made, then scout your enemy."],
      ["8/20", "ud-death-knight", "Make your Death Knight."],
      ["13/20", "ud-ghoul", "Queue 3 additional Ghouls and have them harvest lumber."],
      ["17/20", "nt-attack", "When the DK pops out buy a Rod of Necromancy and go to the Night Elf base. Versus a Demon Hunter skill Unholy Aura first, otherwise Death Coil first."],
      ["19/20", "ne-wisp", "While harassing, kill wood Wisps to interrupt the wood economy. One attack plus a Coil kills a Wisp; attack before coiling."],
      ["19/20", "ud-halls-of-the-dead", "Upgrade your Necropolis to tier 2 as soon as you have the resources."],
      ["19/20", "ud-nerubian-tower", "Upgrade your 1st Ziggurat to a Nerubian Tower only if you expect pressure, which you should not since you are the one pressuring."],
      ["19/20", "ud-ziggurat", "Get a 2nd Ziggurat as soon as possible, then a Graveyard and a 2nd Crypt before you are halfway to tier 2 so they finish with it."],
      ["19/30", "ud-gargoyle", "When tier 2 finishes, start pumping Gargoyles from both Crypts."],
      ["23/30", "nt-attack", "As soon as your Gargoyles are out, send them across the map to harass the wood economy and kill buildings under construction."],
      ["?/30", "ud-black-citadel", "Decide whether to stay tier 2 pumping Gargoyles, get a 2nd hero, or tech tier 3."],
    ],
  },
  {
    slug: "ghoul-pull-build-vs-night-elf",
    title: "Ghoul Pull Build vs Night Elf",
    guideId: "guide-1147",
    vsRace: "nightelf",
    difficulty: "intermediate",
    tags: ["ghoul pull", "ghouls", "gargoyles", "cheese"],
    summary:
      "Send the starting Ghoul straight to the Night Elf's creep camp and pull the creeps onto the Ancient of War to cancel it, then mass Ghouls on wood and tech into Gargoyles.",
    description: [
      "This build is a strategy to be used only versus Night Elf, to cancel or slow their Ancient of War creeping. As the build outlines, you must go straight with your Ghoul to where the Night Elf is creeping in order to pull in time. If you fail to pull the creep or find the Ancient of War you are far behind because of the missing wood early on.",
      "Intermediate: it requires knowing creep mechanics and where the Night Elf is creeping.",
    ],
    steps: [
      ["5/10", "ud-acolyte", "Send your 3 Acolytes to gold and build 1 Acolyte to send to gold."],
      ["6/10", "ud-ghoul", "Take your Ghoul right away and send it to the camp you think the Night Elf will creep with the Ancient of War."],
      ["6/10", "ud-crypt", "Use one of the first Acolytes to make a Crypt and an Altar."],
      ["6/10", "ud-ziggurat", "Build a Ziggurat before getting another Acolyte."],
      ["6/10", "ud-acolyte", "Get a 2nd Acolyte and put it on gold so you have 5/5 on gold."],
      ["7/10", "ne-ancient-of-war", "Find the Ancient of War. Aggro the creep with your Ghoul, pull it to the Ancient, then attack the Ancient so the creep does too. Repeat until it is cancelled."],
      ["7/20", "ud-death-knight", "Build your Death Knight and start making Ghouls to harvest wood."],
      ["14/20", "ud-necropolis", "As soon as you have the gold for a second Necropolis, build it."],
      ["14/20", "nt-attack", "Send your Death Knight across the map to harass."],
      ["14/20", "ud-ghoul", "Continue pumping Ghouls and send them to harvest wood."],
      ["14/20", "ud-nerubian-tower", "Upgrade your Ziggurat to a Nerubian Tower if you think pressure is coming."],
      ["22/30", "ud-halls-of-the-dead", "Once you have about 6-7 Ghouls, begin your tech to tier 2. Get the Nerubian Tower right after if you have not already."],
      ["24/30", "ud-ghoul", "Slow down on Ghoul production, but you can continue getting more."],
      ["24/30", "ud-tomb-of-relics", "Get your Tomb of Relics, Graveyard, a 2nd Ziggurat and then a 2nd Crypt (started around halfway to tier 2)."],
      ["28/40", "ud-gargoyle", "Build Gargoyles at tier 2 and use them to harass the wood Wisps."],
      ["?/40", "ud-black-citadel", "Decide whether to stay tier 2 pumping Gargoyles, get a 2nd hero, or tech tier 3."],
    ],
  },
  {
    slug: "dk-ghoul-tech-vs-dh-naga-panda-1-base",
    title: "DK Ghoul Tech vs DH Naga/Panda 1 Base",
    guideId: "guide-1487",
    vsRace: "nightelf",
    difficulty: "intermediate",
    tags: ["ghouls", "death knight", "tier 3", "one base"],
    summary:
      "Death Knight with Ghouls on one base against a one-base Night Elf: creep to 23 food, tech straight through to tier 3 for the orb and a third hero, with Ghouls doubling as defence.",
    description: [
      "This build allows a relatively quick tier 3 to access your orb and third hero, but is also very safe: multiple Ghouls can be used for base defence and creeping. Great potential for high hero levels and a fun combination of units to fight with.",
      "Intermediate. Requires micro and timing.",
    ],
    steps: [
      ["5/10", "ud-acolyte", "Queue the 1st Acolyte immediately, send Acolytes to gold and your Ghoul to wood."],
      ["6/10", "ud-altar", "Use the starting Acolyte to build an Altar and a Crypt."],
      ["6/10", "ud-ziggurat", "Build a Ziggurat as soon as gold allows (150)."],
      ["6/10", "ud-acolyte", "Build a 5th Acolyte."],
      ["7/10", "ud-tomb-of-relics", "Build a 6th Acolyte to build the shop and scout the Ancient of War position and starting hero. Keep it nearby and try not to lose it."],
      ["15/20", "ud-death-knight", "Start the Death Knight and the 1st Ghoul from your Crypt."],
      ["15/20", "ud-ziggurat", "Make a 2nd Ziggurat and continue making Ghouls until 23 food."],
      ["19/20", "nt-creep", "When the DK pops out, buy a Rod of Necromancy and take 3 Ghouls to creep your nearest green camp (not the smallest of the two)."],
      ["19/30", "ud-ghoul", "Go to 23 food with Ghouls while continuing to creep."],
      ["23/30", "ud-halls-of-the-dead", "Start the tier 2 tech."],
      ["23/30", "ud-graveyard", "Continue to creep and make Ghouls to 30 food (the Acolyte will die to free up space). Get a Graveyard and 3rd Ziggurat."],
      ["30/40", "nt-tavern", "Decide: be aggressive before tier 2, aggressive with Naga second, or grab Lich second and play passively. Get the second hero when you hit tier 2."],
      ["35/40", "nt-scout", "Scout the Night Elf side of the map for a possible expansion."],
      ["35/40", "ud-black-citadel", "Get tier 3, then Slaughterhouse, then Ziggurat in that order."],
      ["35/50", "ud-crypt-fiend", "Get a Fiend and a Statue as soon as possible. Get a 2nd Statue right after."],
      ["41/50", "ud-obsidian-statue", "The 2nd Statue should finish just before tier 3 hits."],
      ["44/50", "nt-upgrade", "Get Lich or Naga third (whichever you did not get), Ghoul Frenzy and Destroyer Form right away."],
      ["49/50", "ud-lich", "Buy the orb with the Lich. Take the red spot and fight the Night Elf with attack upgrades, more Fiends and 3-4 Statues; morph Statues to focus Bears."],
    ],
  },
  {
    slug: "dk-ghoul-expo-vs-ne",
    title: "DK Ghoul Expo vs NE",
    guideId: "guide-1494",
    vsRace: "nightelf",
    difficulty: "intermediate",
    tags: ["ghouls", "death knight", "expansion"],
    summary:
      "Death Knight and four Ghouls creep your natural at 19 food and drop a haunted mine on a Sacrificial Skull, then tower it up and tech to Gargoyles, Statues and Frost Wyrms for the ultra-late game.",
    description: [
      "Death Knight Ghouls with an early expansion lets an Undead thrive in the ultra-late game. However, an early expansion leaves you exposed to Night Elf pressure, and it is more practical on some maps than others. Part of this build is learning when to cut your losses: if you cannot hold the expansion there is a point at which you can tech and not be too far behind.",
      "Intermediate. You must be able to defend your expansion or you will be severely behind.",
    ],
    steps: [
      ["5/10", "ud-acolyte", "Queue the 1st Acolyte immediately, send Acolytes to gold and your Ghoul to wood."],
      ["6/10", "ud-altar", "Use the starting Acolyte to build an Altar and a Crypt."],
      ["6/10", "ud-ziggurat", "Build a Ziggurat as soon as gold allows (150)."],
      ["6/10", "ud-acolyte", "Build a 5th Acolyte (you should have 5/5 on gold now)."],
      ["7/10", "ud-tomb-of-relics", "Build a 6th Acolyte to build the shop, kill any critters between your base and your natural, then return to base."],
      ["8/20", "ud-death-knight", "Start the Death Knight and the 1st Ghoul from your Crypt."],
      ["15/20", "ud-ziggurat", "Make a 2nd Ziggurat and continue making Ghouls that you send to harvest lumber."],
      ["19/20", "nt-creep", "DK out: sell the TP, buy a Rod, 2 Sacrificial Skulls and Dust, creep your expansion with 4 Ghouls. Sell the Altar, bring the 6th Acolyte. Coil aggressively."],
      ["19/20", "ud-haunted-mine", "While creeping, plant a Skull and place a Ziggurat facing the Night Elf side before the Haunted Gold Mine. Scout mid, their expansion and main with a skeleton."],
      ["19/30", "ud-ghoul", "Continue to make Ghouls, rally them to wood and get another Acolyte."],
      ["22/30", "ud-ghoul", "Continue to make Ghouls to 28 food. Weave in Acolytes whenever gold allows, but prioritise Ghouls."],
      ["30/40", "ud-nerubian-tower", "7-8 Ghouls and 3-4 Acolytes on the expansion by now. Upgrade the expo Ziggurat to a Nerubian Tower, get a Graveyard in base and the last expo Acolytes."],
      ["35/40", "ud-halls-of-the-dead", "Tech to tier 2. Add a 2nd Crypt and another tower at your expansion. Rebuild the Altar in main. Get Creature Attack."],
      ["35/40", "ud-crypt", "This is where you decide between 3 Crypt Gargoyles or standard play."],
      ["35/40", "nt-scout", "Scout proactively for a counter expansion. If the Night Elf is creeping it, run to their main and destroy the lumber economy and buildings in progress."],
      ["35/50", "ud-gargoyle", "Make Gargoyles and a Lich immediately at tier 2. Tech tier 3 immediately as well and add a Slaughterhouse."],
      ["44/50", "ud-obsidian-statue", "Get 1 more Gargoyle and 1 Statue. Get the 2nd Creature Attack upgrade. Add 2 more Ziggurats. Continue to creep safely."],
      ["49/70", "ud-frost-wyrm", "Many compositions work against Night Elf; the simplest is Gargoyles from 2 Crypts, 2 Statues, 2 Frost Wyrms and Dreadlord third."],
    ],
  },
  {
    slug: "dk-ghoul-tech-push-vs-kotg-dh-expo",
    title: "DK Ghoul Tech Push vs KotG DH Expo",
    guideId: "guide-1497",
    vsRace: "nightelf",
    difficulty: "advanced",
    tags: ["ghouls", "timing push", "harass", "tier 3"],
    summary:
      "Steal creeps with the Death Knight while Ghouls farm at home, Lich second, then tier 3 with Destroyer form, Ghoul Frenzy and Tinker third to push the Night Elf expansion at 50 food.",
    description: [
      "This build revolves around attacking before the Night Elf expansion pays off and they amass too large an army to stop. You constantly harass up until mid tier 2 or tier 3 while creeping with your Ghouls without your hero, getting the Death Knight to level 2 or 3 between the harass and creeps. If you miss your timing or fail to do damage, the Night Elf will outmass you late.",
      "Advanced. You must multitask and hit the correct timings: farm with your Ghouls while harassing, and hit before the Night Elf is out of reach.",
    ],
    steps: [
      ["5/10", "ud-acolyte", "Queue 2 Acolytes immediately, send Acolytes to gold and your Ghoul to wood."],
      ["6/10", "ud-altar", "Use the starting Acolyte to build an Altar and a Ziggurat."],
      ["7/10", "ud-crypt", "Use the 5th Acolyte (the one that just finished training) to build a Crypt."],
      ["7/10", "ud-tomb-of-relics", "Build a 6th Acolyte to build the shop and scout the Ancient of War position and starting hero. Keep it nearby and try not to lose it."],
      ["15/20", "ud-death-knight", "Start the Death Knight and the 1st Ghoul from your Crypt."],
      ["15/20", "ud-ziggurat", "Make a 2nd Ziggurat and continue making Ghouls until 23 food."],
      ["19/20", "nt-attack", "When the DK pops out, buy a Rod of Necromancy and head straight to the Night Elf side. Steal as many level 2+ creeps as possible, highest level first."],
      ["21/30", "nt-upgrade", "Get the Backpack."],
      ["23/30", "ud-halls-of-the-dead", "Start the tier 2 tech and use your 6 Ghouls to creep the nearest green camp. Pick up items with your Ghouls."],
      ["23/30", "ud-ghoul", "Go to 29 food with Ghouls (3 more)."],
      ["25/30", "nt-scroll-of-town-portal", "The DK is likely low on mana and HP from harassing, so grab a Staff of Teleportation to save Acolytes from Keeper harass or to bail out Ghouls."],
      ["27/30", "ud-graveyard", "Make a Graveyard and then the 3rd Ziggurat."],
      ["29/30", "nt-creep", "With 4 medium-health Ghouls from the first camp and 3 fresh ones, creep a larger camp (ideally a natural like the ogre magi and trappers on Last Refuge)."],
      ["29/30", "ud-acolyte", "The scouting Acolyte is usually dead by now; if not, let it die to a creep camp."],
      ["28/40", "ud-lich", "Get the Lich as soon as possible, tech tier 3, then Slaughterhouse, then 4th Ziggurat in that order."],
      ["33/40", "nt-attack", "Once the Lich is out, buy a Rod of Necromancy (consider situational items) and keep harassing with both heroes, prioritising their 2nd hero."],
      ["39/50", "ud-crypt-fiend", "Make the 1st Fiend and 1st Statue. Get the 2nd Statue immediately after the first."],
      ["42/50", "ud-obsidian-statue", "The 2nd Statue finishes just before tier 3. Queue Destroyer Form and Ghoul Frenzy immediately. Return to buy the Orb of Corruption."],
      ["42/50", "nt-goblin-tinker", "Get a 2nd Fiend, a mana potion for the DK and the 5th Ziggurat. Grab the Tinker as 3rd hero."],
      ["50/60", "nt-attack", "Push down the Night Elf expansion. Positioning is key. Morph 1 Statue into a Destroyer and add another Statue and Fiend while fighting."],
    ],
  },
  {
    slug: "dk-ghoul-tier-3-expo-vs-kotg-dh",
    title: "DK Ghoul Tier 3 Expo vs KotG DH",
    guideId: "guide-1500",
    vsRace: "nightelf",
    difficulty: "advanced",
    tags: ["ghouls", "harass", "tier 3", "expansion", "banshees"],
    summary:
      "Harass with the Death Knight and Lich while teching straight to tier 3, then take your own expansion on a Sacrificial Skull and move into Banshees, Fiends and an Abomination for the late game.",
    description: [
      "This build lets you tech tier 3 while harassing. Your aim is to slow the Night Elf creeping, steal experience and hopefully slow their expansion as a result. You reach tier 3 relatively quickly, get the orb and set up a counter expansion, which together with a good harass puts you in position for the late game.",
      "Advanced. You must multitask and micro the Death Knight while harassing and creep with your Ghouls alone.",
    ],
    steps: [
      ["5/10", "ud-acolyte", "Queue 2 Acolytes immediately, send Acolytes to gold and your Ghoul to wood."],
      ["6/10", "ud-altar", "Use the starting Acolyte to build an Altar and a Ziggurat."],
      ["7/10", "ud-crypt", "Use the 5th Acolyte (the one that just finished training) to build a Crypt."],
      ["7/10", "ud-tomb-of-relics", "Build a 6th Acolyte to build the shop and scout the Ancient of War position and starting hero."],
      ["15/20", "ud-death-knight", "Start the Death Knight and the 1st Ghoul from your Crypt."],
      ["15/20", "ud-ziggurat", "Make a 2nd Ziggurat and make Ghouls until 23 food, putting all Ghouls on wood."],
      ["19/20", "nt-attack", "When the DK pops out, buy a Rod of Necromancy and head straight to the Night Elf side. Steal creeps when possible, highest level first."],
      ["21/30", "nt-upgrade", "Get the Backpack."],
      ["23/30", "ud-halls-of-the-dead", "Start the tier 2 tech and use your 6 Ghouls to creep the nearest green camp. Pick up items with your Ghouls."],
      ["23/30", "ud-ghoul", "Go to 29 food with Ghouls (3 more)."],
      ["25/30", "nt-scroll-of-town-portal", "The DK is likely low on mana and HP from harassing, so grab a Staff of Teleportation to save Acolytes from Keeper harass or to bail out Ghouls."],
      ["27/30", "ud-graveyard", "Make a Graveyard and then the 3rd Ziggurat."],
      ["29/30", "nt-creep", "With 4 medium-health Ghouls from the first camp and 3 new ones, creep a larger camp (ideally a natural camp such as the one on Last Refuge)."],
      ["29/40", "ud-lich", "Get the Lich immediately, tech tier 3, then Slaughterhouse, then 4th Ziggurat in that order."],
      ["34/40", "nt-attack", "Once the Lich is out, buy a Rod of Necromancy and keep harassing with both heroes, prioritising their 2nd hero."],
      ["34/50", "ud-crypt-fiend", "Make the 1st Fiend and 1st Statue. Get the 2nd Statue immediately after the first."],
      ["43/50", "ud-obsidian-statue", "The 2nd Statue finishes just before tier 3. Queue Destroyer Form and Ghoul Frenzy. Return to buy the Orb of Corruption and a Sacrificial Skull."],
      ["43/50", "ud-haunted-mine", "Use the scouting Acolyte to build a Haunted Gold Mine and a Ziggurat first, then a Necropolis. Use the Skull to get an early Nerubian Tower up."],
      ["43/50", "nt-creep", "Creep defensively, but aim to take the red spot as it is easy to clear now."],
      ["43/50", "ud-obsidian-statue", "Get another Statue and Fiend. Scout the Night Elf base to see if they tech tier 3."],
      ["49/50", "ud-temple-of-the-damned", "If the expansion is secure and the elf is going tier 3, make 2 Temples of the Damned towards Master Banshees."],
      ["?/60", "ud-banshee", "Saturate the expansion, mass Banshees (Adept then Master), 1 Abomination and Fiends. Possess Bears and focus Dryads; the Keeper is always a nuke target."],
    ],
  },
  {
    slug: "facing-paladin-rifle-as-undead",
    title: "Facing Paladin Rifle as Undead",
    guideId: "guide-7160",
    vsRace: "human",
    difficulty: "intermediate",
    tags: ["crypt lord", "ghouls", "expansion", "anti-rifle"],
    summary:
      "Crypt Lord Ghoul opening that scouts the Paladin, creeps the natural with skeletons and beetles, expands and towers up, then out-produces the Rifles with Ghoul Frenzy and a Lich orb at tier 3.",
    author: "EchoGoodman",
    description: [
      "Written by EchoGoodman with contributions from Ves. This strategy is proven up to Grandmaster level: simple in its idea, but it requires execution. It assumes a Crypt Lord Ghoul opening, since the Crypt Lord is viable against both Archmage Footmen and Paladin Riflemen. A 6th Acolyte scouts; once you see a Blacksmith and a Paladin, this plan kicks in.",
      "The idea is to out-produce the opponent with lots of Ghouls and summons and buy time for superior upgrades. After the opening the priorities are: scout the Paladin, defend the haunted mine if he tries to cancel it, and creep the Crypt Lord to level 3. The guide covers the defence against the death push and the late game in detail.",
    ],
    steps: [
      ["5/10", "ud-acolyte", "Send Acolytes to gold, the Ghoul to lumber."],
      ["5/10", "ud-acolyte", "Produce a 4th Acolyte, send it to the gold mine."],
      ["6/10", "ud-crypt", "Build a Crypt and an Altar."],
      ["6/10", "ud-ziggurat", "Build a Ziggurat."],
      ["6/10", "ud-acolyte", "Build a 5th Acolyte, send it to the gold mine."],
      ["7/10", "ud-acolyte", "Build a 6th Acolyte."],
      ["8/10", "ud-tomb-of-relics", "Build a Tomb of Relics with the 6th Acolyte."],
      ["8/10", "nt-scout", "The 6th Acolyte kills a critter near the closest big creep camp, then goes to scout the Human base."],
      ["10/10", "ud-ghoul", "Produce a 2nd Ghoul."],
      ["10/20", "ud-crypt-lord", "Produce the Crypt Lord."],
      ["15/20", "ud-ziggurat", "Build a 2nd Ziggurat."],
      ["15/20", "ud-ghoul", "Produce 2 Ghouls."],
      ["19/20", "nt-scout", "By now the scout has seen the Paladin Rifle build. Send the scouting Acolyte back to your closest natural expansion gold mine."],
      ["19/20", "ud-crypt-lord", "The Crypt Lord sells the Town Portal and buys a Rod, a Sacrificial Skull and a Dagger."],
      ["19/20", "nt-creep", "Summon skeletons from the critter body. Pull 1 Ghoul from lumber and creep a green camp with the Crypt Lord (or skip straight to the expansion with 2 Ghouls)."],
      ["21/30", "ud-ghoul", "Produce 4 Ghouls up to 27/30."],
      ["27/30", "nt-expansion", "After the green camp, pull 3 more Ghouls (4 total) and creep your natural. Get as many beetles and skeletons as you can on the way."],
      ["27/30", "ud-haunted-mine", "Use the Skull near the gold mine to build a Ziggurat, haunt the mine as soon as you can afford it and upgrade the Ziggurat to a Nerubian Tower."],
      ["?/40", "ud-halls-of-the-dead", "When the expansion saturates (around 5:10-5:30): tech tier 2, Graveyard, Necropolis at the expo, 2nd Crypt, 2 Ziggurats at the expo, towers in both bases."],
      ["?/50", "ud-ghoul", "Keep producing Ghouls throughout, up to 45 supply at most, leaving 5 supply for the 2nd hero before upkeep."],
      ["?/50", "ud-black-citadel", "At tier 2 immediately tech tier 3, make the Death Knight and build a Slaughterhouse. You are aiming for Ghoul Frenzy and a Lich with orb as 3rd hero."],
    ],
  },
  {
    slug: "crypt-lord-fast-fiends-fast-tech",
    title: "Crypt Lord Fast Fiends with Fast Tech",
    guideId: "guide-7183",
    vsRace: "any",
    difficulty: "beginner",
    tags: ["crypt lord", "fiends", "fast tech", "timing push"],
    summary:
      "Crypt Lord first with Fiends and a fast tier 2: beetles scout and pull camps, a Tavern hero second, then a 42 food push with six Fiends, a Statue and a Meat Wagon.",
    author: "NorthDrakkar",
    description: [
      "This guide focuses on a Crypt Lord first build with a fast tech to tier 2 and a push using Crypt Fiends. It is designed to be beginner-friendly, requiring minimal micro in fights and letting you focus on macro. It works especially well as an early push with a Tavern hero second and is effective in various matchups.",
      "Beginner: requires little micro and focuses on macro management.",
    ],
    steps: [
      ["5/10", "ud-crypt", "Acolytes to gold, Ghoul to wood, build a Crypt and a Graveyard, queue the 4th Acolyte."],
      ["6/10", "ud-acolyte", "Queue the 5th Acolyte instantly after the 4th one completes."],
      ["7/10", "ud-altar", "Build an Altar of Darkness, build a Ziggurat and queue a second Ghoul."],
      ["9/20", "ud-crypt-lord", "Build a Tomb of Relics, start the Crypt Lord and queue a 3rd Ghoul."],
      ["9/20", "ud-ziggurat", "Build a 2nd Ziggurat."],
      ["16/20", "ud-crypt-fiend", "Queue a Crypt Fiend."],
      ["19/20", "ud-halls-of-the-dead", "Tech to tier 2, skill Carrion Beetles (autocast for now), scout with the first beetles (expo and main) and pull the nearest camp to your main with the Fiend."],
      ["19/20", "nt-creep", "Buy a Rod on the Crypt Lord, summon skeletons, creep with the Fiend, 2 skeletons and the 2nd set of beetles. Send the 3rd set of beetles to harass."],
      ["19/30", "ud-crypt-fiend", "Queue the 2nd Crypt Fiend."],
      ["22/30", "ud-ziggurat", "Move on to the next camp (closest orange or consumable camp), build the 3rd Ziggurat and queue the 3rd Crypt Fiend."],
      ["25/30", "ud-crypt-fiend", "Queue the 4th Crypt Fiend."],
      ["28/30", "ud-ziggurat", "Build the 4th Ziggurat."],
      ["28/40", "ud-slaughterhouse", "Tier 2 reached: research Burrow and queue a Slaughterhouse."],
      ["28/50", "ud-crypt-fiend", "Queue the 5th Crypt Fiend."],
      ["31/50", "nt-tavern", "Head to the Tavern, hire a Naga Sea Witch or Dark Ranger, and queue 1 Obsidian Statue."],
      ["39/50", "ud-crypt-fiend", "Queue the 6th Crypt Fiend."],
      ["42/50", "nt-attack", "Move to attack the enemy main or expansion."],
      ["45/50", "ud-meat-wagon", "Queue a Meat Wagon for siege and research the Crypt Fiend attack upgrade."],
      ["48/50", "ud-black-citadel", "Research Web and tech to tier 3."],
    ],
  },
  {
    slug: "pit-lord-fast-t3-necro-wagon-push",
    title: "Pit Lord Fast T3 Necro Wagon Push",
    guideId: "guide-7384",
    vsRace: "any",
    difficulty: "intermediate",
    tags: ["pit lord", "necromancers", "meat wagons", "off-meta", "tier 3"],
    summary:
      "Off-meta Ghoul opening into a Tavern Pit Lord, two Temples of the Damned and a fast tier 3, sieging around the 10 minute mark with eight Necromancers, two Meat Wagons and two Statues.",
    author: "Nio of Ida",
    description: [
      "Created by Nio of Ida (aka SilversGodot). This strategy combines the sustain and attrition of Necromancer Meat Wagons with the Pit Lord's Cleave. It is highly off-meta and likely not viable above 1600 MMR, but it is playable below that. Most feasible versus Human and Night Elf; the Orc matchup is playable but harder.",
      "Intermediate: at lower levels micro is not the deciding factor, but good control of the army and hero are needed to climb.",
    ],
    steps: [
      ["5/10", "ud-crypt", "Acolytes to gold, Ghoul to wood, build a Crypt and an Altar, queue the 4th Acolyte."],
      ["6/10", "ud-acolyte", "Queue the 5th Acolyte instantly after the 4th one completes."],
      ["7/10", "ud-ziggurat", "Build the 1st Ziggurat and a Tomb of Relics, then research the Backpack upgrade."],
      ["7/20", "ud-ghoul", "Queue the 2nd and 3rd Ghoul once the Crypt is built."],
      ["11/20", "ud-ghoul", "Queue the 4th Ghoul, rallied to the closest Tavern."],
      ["13/20", "nt-tavern", "Buy a Rod on the 4th Ghoul, pull another Ghoul towards the Tavern."],
      ["13/20", "ud-ghoul", "Queue the 5th Ghoul."],
      ["15/20", "nt-pit-lord", "Hire the Pit Lord from the Tavern."],
      ["20/20", "ud-halls-of-the-dead", "Start the tier 2 tech, build a Graveyard and a 2nd Ziggurat."],
      ["20/30", "ud-temple-of-the-damned", "Tier 2: build a Slaughterhouse and 2 Temples of the Damned."],
      ["20/30", "nt-lumber", "Make sure all 5 Ghouls are on lumber."],
      ["20/30", "ud-ziggurat", "Build the 3rd Ziggurat."],
      ["20/30", "ud-necromancer", "Queue 1 Meat Wagon and 2 Necromancers."],
      ["28/30", "ud-black-citadel", "Start the tier 3 tech."],
      ["28/30", "ud-ziggurat", "Build the 4th Ziggurat."],
      ["28/40", "ud-meat-wagon", "Queue 2 more Necromancers and the 2nd Meat Wagon."],
      ["40/50", "ud-obsidian-statue", "Queue the 1st Obsidian Statue and 2 more Necromancers."],
      ["47/50", "nt-upgrade", "Build the 5th Ziggurat, queue Necromancer Adept Training, Skeletal Mastery and Exhume Corpses."],
      ["47/50", "ud-obsidian-statue", "Queue the 2nd Obsidian Statue."],
      ["50/50", "nt-upgrade", "Tier 3 reached: queue Necromancer Master Training and Disease Cloud."],
      ["50/50", "nt-attack", "Siege the enemy base around the 10 minute mark with the Pit Lord, 8 Necromancers, 2 Meat Wagons, 2 Obsidian Statues and Ghouls."],
    ],
  },
];
